package corbaObjects.letstalk;

/**
 * corbaObjects/letstalk/CommFacetPOA.java . Generated by the IDL-to-Java
 * compiler (portable), version "3.2" from letstalk.idl Sexta-feira, 9 de
 * Dezembro de 2005 18h26min29s BRST
 */

public abstract class CommFacetPOA extends org.omg.PortableServer.Servant
		implements corbaObjects.letstalk.CommFacetOperations,
		org.omg.CORBA.portable.InvokeHandler {

	// Constructors

	private static java.util.Hashtable _methods = new java.util.Hashtable();

	static {
		_methods.put("startChatting", new java.lang.Integer(0));
		_methods.put("sendMessage", new java.lang.Integer(1));
	}

	public org.omg.CORBA.portable.OutputStream _invoke(String $method,
			org.omg.CORBA.portable.InputStream in,
			org.omg.CORBA.portable.ResponseHandler $rh) {
		org.omg.CORBA.portable.OutputStream out = null;
		java.lang.Integer __method = (java.lang.Integer) _methods.get($method);
		if (__method == null)
			throw new org.omg.CORBA.BAD_OPERATION(0,
					org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

		switch (__method.intValue()) {
		case 0: // corbaObjects/letstalk/CommFacet/startChatting
		{
			try {
				String login = in.read_string();
				String users[] = corbaObjects.letstalk.stringListHelper
						.read(in);
				this.startChatting(login, users);
				out = $rh.createReply();
			} catch (corbaObjects.scs.InvalidConnection $ex) {
				out = $rh.createExceptionReply();
				corbaObjects.scs.InvalidConnectionHelper.write(out, $ex);
			} catch (corbaObjects.scs.InternalError $ex) {
				out = $rh.createExceptionReply();
				corbaObjects.scs.InternalErrorHelper.write(out, $ex);
			}
			break;
		}

		case 1: // corbaObjects/letstalk/CommFacet/sendMessage
		{
			try {
				String login = in.read_string();
				String chatId = in.read_string();
				String recipients[] = corbaObjects.letstalk.stringListHelper
						.read(in);
				String message = in.read_string();
				this.sendMessage(login, chatId, recipients, message);
				out = $rh.createReply();
			} catch (corbaObjects.scs.InternalError $ex) {
				out = $rh.createExceptionReply();
				corbaObjects.scs.InternalErrorHelper.write(out, $ex);
			} catch (corbaObjects.scs.InvalidName $ex) {
				out = $rh.createExceptionReply();
				corbaObjects.scs.InvalidNameHelper.write(out, $ex);
			}
			break;
		}

		default:
			throw new org.omg.CORBA.BAD_OPERATION(0,
					org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
		}

		return out;
	} // _invoke

	// Type-specific CORBA::Object operations
	private static String[] __ids = { "IDL:corbaObjects/letstalk/CommFacet:1.0" };

	public String[] _all_interfaces(org.omg.PortableServer.POA poa,
			byte[] objectId) {
		return __ids.clone();
	}

	public CommFacet _this() {
		return CommFacetHelper.narrow(super._this_object());
	}

	public CommFacet _this(org.omg.CORBA.ORB orb) {
		return CommFacetHelper.narrow(super._this_object(orb));
	}

} // class CommFacetPOA
