package corbaObjects.letstalk;

/**
 * corbaObjects/letstalk/InvalidSubscriptionValues.java . Generated by the
 * IDL-to-Java compiler (portable), version "3.2" from letstalk.idl Sexta-feira,
 * 9 de Dezembro de 2005 18h26min29s BRST
 */

public final class InvalidSubscriptionValues extends
		org.omg.CORBA.UserException {

	public InvalidSubscriptionValues() {
		super(InvalidSubscriptionValuesHelper.id());
	} // ctor

	public InvalidSubscriptionValues(String $reason) {
		super(InvalidSubscriptionValuesHelper.id() + "  " + $reason);
	} // ctor

} // class InvalidSubscriptionValues
