package corbaObjects.letstalk;

/**
 * corbaObjects/letstalk/ServerCallBackFacetHelper.java . Generated by the
 * IDL-to-Java compiler (portable), version "3.2" from letstalk.idl Sexta-feira,
 * 9 de Dezembro de 2005 18h26min29s BRST
 */

abstract public class ServerCallBackFacetHelper {
	private static String _id = "IDL:corbaObjects/letstalk/ServerCallBackFacet:1.0";

	public static void insert(org.omg.CORBA.Any a,
			corbaObjects.letstalk.ServerCallBackFacet that) {
		org.omg.CORBA.portable.OutputStream out = a.create_output_stream();
		a.type(type());
		write(out, that);
		a.read_value(out.create_input_stream(), type());
	}

	public static corbaObjects.letstalk.ServerCallBackFacet extract(
			org.omg.CORBA.Any a) {
		return read(a.create_input_stream());
	}

	private static org.omg.CORBA.TypeCode __typeCode = null;

	synchronized public static org.omg.CORBA.TypeCode type() {
		if (__typeCode == null) {
			__typeCode = org.omg.CORBA.ORB.init().create_interface_tc(
					corbaObjects.letstalk.ServerCallBackFacetHelper.id(),
					"ServerCallBackFacet");
		}
		return __typeCode;
	}

	public static String id() {
		return _id;
	}

	public static corbaObjects.letstalk.ServerCallBackFacet read(
			org.omg.CORBA.portable.InputStream istream) {
		return narrow(istream.read_Object(_ServerCallBackFacetStub.class));
	}

	public static void write(org.omg.CORBA.portable.OutputStream ostream,
			corbaObjects.letstalk.ServerCallBackFacet value) {
		ostream.write_Object(value);
	}

	public static corbaObjects.letstalk.ServerCallBackFacet narrow(
			org.omg.CORBA.Object obj) {
		if (obj == null)
			return null;
		else if (obj instanceof corbaObjects.letstalk.ServerCallBackFacet)
			return (corbaObjects.letstalk.ServerCallBackFacet) obj;
		else if (!obj._is_a(id()))
			throw new org.omg.CORBA.BAD_PARAM();
		else {
			org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)
					._get_delegate();
			corbaObjects.letstalk._ServerCallBackFacetStub stub = new corbaObjects.letstalk._ServerCallBackFacetStub();
			stub._set_delegate(delegate);
			return stub;
		}
	}

	public static corbaObjects.letstalk.ServerCallBackFacet unchecked_narrow(
			org.omg.CORBA.Object obj) {
		if (obj == null)
			return null;
		else if (obj instanceof corbaObjects.letstalk.ServerCallBackFacet)
			return (corbaObjects.letstalk.ServerCallBackFacet) obj;
		else {
			org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)
					._get_delegate();
			corbaObjects.letstalk._ServerCallBackFacetStub stub = new corbaObjects.letstalk._ServerCallBackFacetStub();
			stub._set_delegate(delegate);
			return stub;
		}
	}

}
