package corbaObjects.letstalk;

/**
 * corbaObjects/letstalk/ServerCallBackFacetPOA.java . Generated by the
 * IDL-to-Java compiler (portable), version "3.2" from letstalk.idl Sexta-feira,
 * 9 de Dezembro de 2005 18h26min29s BRST
 */

public abstract class ServerCallBackFacetPOA extends
		org.omg.PortableServer.Servant implements
		corbaObjects.letstalk.ServerCallBackFacetOperations,
		org.omg.CORBA.portable.InvokeHandler {

	// Constructors

	private static java.util.Hashtable _methods = new java.util.Hashtable();

	static {
		_methods.put("receiveMessage", new java.lang.Integer(0));
		_methods.put("updateDirectory", new java.lang.Integer(1));
	}

	public org.omg.CORBA.portable.OutputStream _invoke(String $method,
			org.omg.CORBA.portable.InputStream in,
			org.omg.CORBA.portable.ResponseHandler $rh) {
		org.omg.CORBA.portable.OutputStream out = null;
		java.lang.Integer __method = (java.lang.Integer) _methods.get($method);
		if (__method == null)
			throw new org.omg.CORBA.BAD_OPERATION(0,
					org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

		switch (__method.intValue()) {
		case 0: // corbaObjects/letstalk/ServerCallBackFacet/receiveMessage
		{
			try {
				String user = in.read_string();
				String chatId = in.read_string();
				String userId[] = corbaObjects.letstalk.stringListHelper
						.read(in);
				String message = in.read_string();
				this.receiveMessage(user, chatId, userId, message);
				out = $rh.createReply();
			} catch (corbaObjects.scs.InternalError $ex) {
				out = $rh.createExceptionReply();
				corbaObjects.scs.InternalErrorHelper.write(out, $ex);
			}
			break;
		}

		case 1: // corbaObjects/letstalk/ServerCallBackFacet/updateDirectory
		{
			try {
				this.updateDirectory();
				out = $rh.createReply();
			} catch (corbaObjects.scs.InternalError $ex) {
				out = $rh.createExceptionReply();
				corbaObjects.scs.InternalErrorHelper.write(out, $ex);
			}
			break;
		}

		default:
			throw new org.omg.CORBA.BAD_OPERATION(0,
					org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
		}

		return out;
	} // _invoke

	// Type-specific CORBA::Object operations
	private static String[] __ids = { "IDL:corbaObjects/letstalk/ServerCallBackFacet:1.0" };

	public String[] _all_interfaces(org.omg.PortableServer.POA poa,
			byte[] objectId) {
		return __ids.clone();
	}

	public ServerCallBackFacet _this() {
		return ServerCallBackFacetHelper.narrow(super._this_object());
	}

	public ServerCallBackFacet _this(org.omg.CORBA.ORB orb) {
		return ServerCallBackFacetHelper.narrow(super._this_object(orb));
	}

} // class ServerCallBackFacetPOA
