package corbaObjects.letstalk;

/**
 * corbaObjects/letstalk/ServerCallBackFacetOperations.java . Generated by the
 * IDL-to-Java compiler (portable), version "3.2" from letstalk.idl Sexta-feira,
 * 9 de Dezembro de 2005 18h26min29s BRST
 */

public interface ServerCallBackFacetOperations {
	void receiveMessage(String user, String chatId, String[] userId,
			String message) throws corbaObjects.scs.InternalError;

	void updateDirectory() throws corbaObjects.scs.InternalError;
} // interface ServerCallBackFacetOperations
