package corbaObjects.letstalk;

/**
 * corbaObjects/letstalk/UserFacet.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from letstalk.idl Sexta-feira, 9 de Dezembro de
 * 2005 18h26min29s BRST
 */

public interface UserFacet extends UserFacetOperations, org.omg.CORBA.Object,
		org.omg.CORBA.portable.IDLEntity {
} // interface UserFacet
