package corbaObjects.letstalk;

/**
 * corbaObjects/letstalk/UserFacetOperations.java . Generated by the IDL-to-Java
 * compiler (portable), version "3.2" from letstalk.idl Sexta-feira, 9 de
 * Dezembro de 2005 18h26min29s BRST
 */

public interface UserFacetOperations {
	void subscribe(String login, String password)
			throws corbaObjects.letstalk.InvalidSubscriptionValues,
			corbaObjects.scs.InternalError;

	int connect(String login, String password, org.omg.CORBA.Object host)
			throws corbaObjects.scs.InvalidName,
			corbaObjects.scs.InvalidConnection,
			corbaObjects.scs.AlreadyConnected,
			corbaObjects.scs.ExceededConnectionLimit,
			corbaObjects.scs.InternalError;

	void disconnect(String login) throws corbaObjects.scs.InvalidConnection,
			corbaObjects.scs.NoConnection, corbaObjects.scs.InternalError;

	String[] listUsers() throws corbaObjects.scs.InternalError;
} // interface UserFacetOperations
