package corbaObjects.letstalk;

/**
 * corbaObjects/letstalk/UserFacetHolder.java . Generated by the IDL-to-Java
 * compiler (portable), version "3.2" from letstalk.idl Sexta-feira, 9 de
 * Dezembro de 2005 18h26min29s BRST
 */

public final class UserFacetHolder implements org.omg.CORBA.portable.Streamable {
	public corbaObjects.letstalk.UserFacet value = null;

	public UserFacetHolder() {
	}

	public UserFacetHolder(corbaObjects.letstalk.UserFacet initialValue) {
		value = initialValue;
	}

	public void _read(org.omg.CORBA.portable.InputStream i) {
		value = corbaObjects.letstalk.UserFacetHelper.read(i);
	}

	public void _write(org.omg.CORBA.portable.OutputStream o) {
		corbaObjects.letstalk.UserFacetHelper.write(o, value);
	}

	public org.omg.CORBA.TypeCode _type() {
		return corbaObjects.letstalk.UserFacetHelper.type();
	}

}
