package uff.ic.letstalk.corbaObjects.letstalk;

/**
 * corbaObjects/letstalk/ServerCallBackFacetHolder.java . Generated by the
 * IDL-to-Java compiler (portable), version "3.2" from letstalk.idl Sexta-feira,
 * 9 de Dezembro de 2005 18h26min29s BRST
 */

public final class ServerCallBackFacetHolder implements
		org.omg.CORBA.portable.Streamable {
	public uff.ic.letstalk.corbaObjects.letstalk.ServerCallBackFacet value = null;

	public ServerCallBackFacetHolder() {
	}

	public ServerCallBackFacetHolder(
			uff.ic.letstalk.corbaObjects.letstalk.ServerCallBackFacet initialValue) {
		value = initialValue;
	}

	public void _read(org.omg.CORBA.portable.InputStream i) {
		value = uff.ic.letstalk.corbaObjects.letstalk.ServerCallBackFacetHelper.read(i);
	}

	public void _write(org.omg.CORBA.portable.OutputStream o) {
		uff.ic.letstalk.corbaObjects.letstalk.ServerCallBackFacetHelper.write(o, value);
	}

	public org.omg.CORBA.TypeCode _type() {
		return uff.ic.letstalk.corbaObjects.letstalk.ServerCallBackFacetHelper.type();
	}

}
