/* Generated by Together */

package iso.iso19115.citation;

/**
 * @stereotype type*/
public class CI_Address {
	public String deliveryPoint = null;

	public String city = null;

	public String administrativeArea = null;

	public String postalCode = null;

	public String country = null;

	public String electronicEmailAddress = null;
}
