/* Generated by Together */

package iso.iso19115.citation;

import java.sql.Date;

/**
 * @stereotype type*/
public class CI_Date {
	/**
	 * @link association
	 * @associates <{CI_DateTypeCode}>*/
	public Date date = null;

	public String dateType = null;
}
