/* Generated by Together */

package iso.iso19115.citation;

import java.net.URL;

/**
 * @stereotype type*/
public class CI_OnLineResource {
	public URL linkage = null;

	public String protocol = null;

	public String applicationProfile = null;

	public String name = null;

	public String description = null;

	/**
	 * @link association
	 * @associates <{CI_OnLineFunctionCode}>*/
	public String function = null;
}
