/* Generated by Together */

package iso.iso19115.citation;

/**
 * @stereotype type*/
public class CI_ResponsibleParty {

	public String individualName = null;

	public String organisationName = null;

	public String positionName = null;
	public CI_Contact contectInfo = null;

	/**
	 * @link association
	 * @associates <{CI_RoleCode}>*/
	public String role = "originator";
}
