/* Generated by Together */

package iso.iso19115.citation;

/**
 * @stereotype type*/
public class CI_Series {
	public String name = null;

	public String issueIdentification = null;

	public String page = null;
}
