package uff.ic.lleme.corba.testes.javaORB.StockObjects;

/**
 * StockObjects/QuoteHolder.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.1" from stock.idl S�bado, 17 de Setembro de 2005
 * 14h14min39s BRT
 */

public final class QuoteHolder implements org.omg.CORBA.portable.Streamable {
	public uff.ic.lleme.corba.testes.javaORB.StockObjects.Quote value = null;

	public QuoteHolder() {
	}

	public QuoteHolder(uff.ic.lleme.corba.testes.javaORB.StockObjects.Quote initialValue) {
		value = initialValue;
	}

	public void _read(org.omg.CORBA.portable.InputStream i) {
		value = uff.ic.lleme.corba.testes.javaORB.StockObjects.QuoteHelper.read(i);
	}

	public void _write(org.omg.CORBA.portable.OutputStream o) {
		uff.ic.lleme.corba.testes.javaORB.StockObjects.QuoteHelper.write(o, value);
	}

	public org.omg.CORBA.TypeCode _type() {
		return uff.ic.lleme.corba.testes.javaORB.StockObjects.QuoteHelper.type();
	}

}
