/* Generated by Together */

package uff.ic.tcc00175.catfwk.model;

/**
 * @version 1.0
 * @since 1.0
 * @author Luiz Andr�
 * @alias Gazetteer
 * @stereotype abstract*/
abstract public class Gazetteer extends DescriptionSource {

	/**
	 * @directed
	 * @label organize desc using
	 * @labelDirection forward*/
	private transient DictionaryDescBuilder builder = null;

	public Gazetteer(String url) {
		super(url);
	}

	/**
	 * @return Returns the builder.
	 */
	public Builder getBuilder() {
		if (builder == null)
			builder = getFactory().createDictionaryDescBuilder();
		return builder;
	}
}
