/**
 * ComponentLoaderPOA.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.2" from deployment.idl Saturday, December 10, 2005 1:24:06 AM GMT
 */

public abstract class ComponentLoaderPOA extends org.omg.PortableServer.Servant
		implements ComponentLoaderOperations,
		org.omg.CORBA.portable.InvokeHandler {

	// Constructors

	private static java.util.Hashtable _methods = new java.util.Hashtable();
	static {
		_methods.put("load", new java.lang.Integer(0));
		_methods.put("unload", new java.lang.Integer(1));
	}

	public org.omg.CORBA.portable.OutputStream _invoke(String $method,
			org.omg.CORBA.portable.InputStream in,
			org.omg.CORBA.portable.ResponseHandler $rh) {
		org.omg.CORBA.portable.OutputStream out = null;
		java.lang.Integer __method = (java.lang.Integer) _methods.get($method);
		if (__method == null)
			throw new org.omg.CORBA.BAD_OPERATION(0,
					org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

		switch (__method.intValue()) {
		case 0: // ComponentLoader/load
		{
			ComponentHandle handle = ComponentHandleHelper.read(in);
			this.load(handle);
			out = $rh.createReply();
			break;
		}

		case 1: // ComponentLoader/unload
		{
			ComponentHandle handle = ComponentHandleHelper.read(in);
			this.unload(handle);
			out = $rh.createReply();
			break;
		}

		default:
			throw new org.omg.CORBA.BAD_OPERATION(0,
					org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
		}

		return out;
	} // _invoke

	// Type-specific CORBA::Object operations
	private static String[] __ids = { "IDL:ComponentLoader:1.0" };

	public String[] _all_interfaces(org.omg.PortableServer.POA poa,
			byte[] objectId) {
		return (String[]) __ids.clone();
	}

	public ComponentLoader _this() {
		return ComponentLoaderHelper.narrow(super._this_object());
	}

	public ComponentLoader _this(org.omg.CORBA.ORB orb) {
		return ComponentLoaderHelper.narrow(super._this_object(orb));
	}

} // class ComponentLoaderPOA
