/**
 * ComponentId.java . Generated by the IDL-to-Java compiler (portable), version
 * "3.2" from deployment.idl Saturday, December 10, 2005 1:24:06 AM GMT
 */

public final class ComponentId implements org.omg.CORBA.portable.IDLEntity {
	public String name = null;

	public int version = (int) 0;

	public ComponentId() {
	} // ctor

	public ComponentId(String _name, int _version) {
		name = _name;
		version = _version;
	} // ctor

} // class ComponentId
