/**
 * ComponentDescription.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.2" from deployment.idl Saturday, December 10, 2005 1:24:06 AM GMT
 */

public final class ComponentDescription implements
		org.omg.CORBA.portable.IDLEntity {
	public ComponentId id = null;

	public String entry_point = null;

	public boolean shared = false;

	public ComponentDescription() {
	} // ctor

	public ComponentDescription(ComponentId _id, String _entry_point,
			boolean _shared) {
		id = _id;
		entry_point = _entry_point;
		shared = _shared;
	} // ctor

} // class ComponentDescription
