/**
 * ComponentHandle.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.2" from deployment.idl Saturday, December 10, 2005 1:24:06 AM GMT
 */

public final class ComponentHandle implements org.omg.CORBA.portable.IDLEntity {
	public IComponent cmp = null;

	public ComponentId id = null;

	public int instance_id = (int) 0;

	public ComponentHandle() {
	} // ctor

	public ComponentHandle(IComponent _cmp, ComponentId _id, int _instance_id) {
		cmp = _cmp;
		id = _id;
		instance_id = _instance_id;
	} // ctor

} // class ComponentHandle
