/**
 * ComponentNotFound.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.2" from deployment.idl Saturday, December 10, 2005 1:24:06 AM GMT
 */

public final class ComponentNotFound extends org.omg.CORBA.UserException {

	public ComponentNotFound() {
		super(ComponentNotFoundHelper.id());
	} // ctor

	public ComponentNotFound(String $reason) {
		super(ComponentNotFoundHelper.id() + "  " + $reason);
	} // ctor

} // class ComponentNotFound
