/**
 * ComponentLoaderHolder.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from deployment.idl Saturday, December 10, 2005
 * 1:24:06 AM GMT
 */

public final class ComponentLoaderHolder implements
		org.omg.CORBA.portable.Streamable {
	public ComponentLoader value = null;

	public ComponentLoaderHolder() {
	}

	public ComponentLoaderHolder(ComponentLoader initialValue) {
		value = initialValue;
	}

	public void _read(org.omg.CORBA.portable.InputStream i) {
		value = ComponentLoaderHelper.read(i);
	}

	public void _write(org.omg.CORBA.portable.OutputStream o) {
		ComponentLoaderHelper.write(o, value);
	}

	public org.omg.CORBA.TypeCode _type() {
		return ComponentLoaderHelper.type();
	}

}
