/**
 * ConnectionDescriptionsHolder.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from scs.idl Friday, December 9, 2005 9:35:21 PM
 * GMT
 */

public final class ConnectionDescriptionsHolder implements
		org.omg.CORBA.portable.Streamable {
	public ConnectionDescription value[] = null;

	public ConnectionDescriptionsHolder() {
	}

	public ConnectionDescriptionsHolder(ConnectionDescription[] initialValue) {
		value = initialValue;
	}

	public void _read(org.omg.CORBA.portable.InputStream i) {
		value = ConnectionDescriptionsHelper.read(i);
	}

	public void _write(org.omg.CORBA.portable.OutputStream o) {
		ConnectionDescriptionsHelper.write(o, value);
	}

	public org.omg.CORBA.TypeCode _type() {
		return ConnectionDescriptionsHelper.type();
	}

}
