/**
 * IComponentPOATie.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.2" from scs.idl Friday, December 9, 2005 9:35:21 PM GMT
 */

public class IComponentPOATie extends IComponentPOA {

	// Constructors

	public IComponentPOATie(IComponentOperations delegate) {
		this._impl = delegate;
	}

	public IComponentPOATie(IComponentOperations delegate,
			org.omg.PortableServer.POA poa) {
		this._impl = delegate;
		this._poa = poa;
	}

	public IComponentOperations _delegate() {
		return this._impl;
	}

	public void _delegate(IComponentOperations delegate) {
		this._impl = delegate;
	}

	public org.omg.PortableServer.POA _default_POA() {
		if (_poa != null) {
			return _poa;
		} else {
			return super._default_POA();
		}
	}

	public org.omg.CORBA.Object getFacet(String facet_interface) {
		return _impl.getFacet(facet_interface);
	} // getFacet

	public org.omg.CORBA.Object getFacetByName(String facet) {
		return _impl.getFacetByName(facet);
	} // getFacetByName

	public void startup() throws StartupFailed {
		_impl.startup();
	} // startup

	public void shutdown() throws ShutdownFailed {
		_impl.shutdown();
	} // shutdown

	// Receptacle
	public int connect(String receptacle, org.omg.CORBA.Object obj)
			throws InvalidName, InvalidConnection, AlreadyConnected,
			ExceededConnectionLimit {
		return _impl.connect(receptacle, obj);
	} // connect

	public void disconnect(int id) throws InvalidConnection, NoConnection {
		_impl.disconnect(id);
	} // disconnect

	public ConnectionDescription getConnection(int id) throws InvalidConnection {
		return _impl.getConnection(id);
	} // getConnection

	public ConnectionDescription[] getConnections(String receptacle)
			throws InvalidName {
		return _impl.getConnections(receptacle);
	} // getConnections

	// MetaInterface
	public FacetDescription[] getFacets() {
		return _impl.getFacets();
	} // getFacets

	public FacetDescription[] getFacetsByName(String[] names)
			throws InvalidName {
		return _impl.getFacetsByName(names);
	} // getFacetsByName

	public ReceptacleDescription[] getReceptacles() {
		return _impl.getReceptacles();
	} // getReceptacles

	public ReceptacleDescription[] getReceptaclesByName(String[] names)
			throws InvalidName {
		return _impl.getReceptaclesByName(names);
	} // getReceptaclesByName

	private IComponentOperations _impl;

	private org.omg.PortableServer.POA _poa;

} // class IComponentPOATie
