/**
 * IComponentOperations.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.2" from scs.idl Friday, December 9, 2005 9:35:21 PM GMT
 */

public interface IComponentOperations {
	org.omg.CORBA.Object getFacet(String facet_interface);

	org.omg.CORBA.Object getFacetByName(String facet);

	void startup() throws StartupFailed;

	void shutdown() throws ShutdownFailed;

	// Receptacle
	int connect(String receptacle, org.omg.CORBA.Object obj)
			throws InvalidName, InvalidConnection, AlreadyConnected,
			ExceededConnectionLimit;

	void disconnect(int id) throws InvalidConnection, NoConnection;

	ConnectionDescription getConnection(int id) throws InvalidConnection;

	ConnectionDescription[] getConnections(String receptacle)
			throws InvalidName;

	// MetaInterface
	FacetDescription[] getFacets();

	FacetDescription[] getFacetsByName(String[] names) throws InvalidName;

	ReceptacleDescription[] getReceptacles();

	ReceptacleDescription[] getReceptaclesByName(String[] names)
			throws InvalidName;
} // interface IComponentOperations
