/**
 * IComponentPOA.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.2" from scs.idl Friday, December 9, 2005 9:35:21 PM GMT
 */

public abstract class IComponentPOA extends org.omg.PortableServer.Servant
		implements IComponentOperations, org.omg.CORBA.portable.InvokeHandler {

	// Constructors

	private static java.util.Hashtable _methods = new java.util.Hashtable();
	static {
		_methods.put("getFacet", new java.lang.Integer(0));
		_methods.put("getFacetByName", new java.lang.Integer(1));
		_methods.put("startup", new java.lang.Integer(2));
		_methods.put("shutdown", new java.lang.Integer(3));
		_methods.put("connect", new java.lang.Integer(4));
		_methods.put("disconnect", new java.lang.Integer(5));
		_methods.put("getConnection", new java.lang.Integer(6));
		_methods.put("getConnections", new java.lang.Integer(7));
		_methods.put("getFacets", new java.lang.Integer(8));
		_methods.put("getFacetsByName", new java.lang.Integer(9));
		_methods.put("getReceptacles", new java.lang.Integer(10));
		_methods.put("getReceptaclesByName", new java.lang.Integer(11));
	}

	public org.omg.CORBA.portable.OutputStream _invoke(String $method,
			org.omg.CORBA.portable.InputStream in,
			org.omg.CORBA.portable.ResponseHandler $rh) {
		org.omg.CORBA.portable.OutputStream out = null;
		java.lang.Integer __method = (java.lang.Integer) _methods.get($method);
		if (__method == null)
			throw new org.omg.CORBA.BAD_OPERATION(0,
					org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

		switch (__method.intValue()) {
		case 0: // IComponent/getFacet
		{
			String facet_interface = in.read_string();
			org.omg.CORBA.Object $result = null;
			$result = this.getFacet(facet_interface);
			out = $rh.createReply();
			org.omg.CORBA.ObjectHelper.write(out, $result);
			break;
		}

		case 1: // IComponent/getFacetByName
		{
			String facet = in.read_string();
			org.omg.CORBA.Object $result = null;
			$result = this.getFacetByName(facet);
			out = $rh.createReply();
			org.omg.CORBA.ObjectHelper.write(out, $result);
			break;
		}

		case 2: // IComponent/startup
		{
			try {
				this.startup();
				out = $rh.createReply();
			} catch (StartupFailed $ex) {
				out = $rh.createExceptionReply();
				StartupFailedHelper.write(out, $ex);
			}
			break;
		}

		case 3: // IComponent/shutdown
		{
			try {
				this.shutdown();
				out = $rh.createReply();
			} catch (ShutdownFailed $ex) {
				out = $rh.createExceptionReply();
				ShutdownFailedHelper.write(out, $ex);
			}
			break;
		}

		// Receptacle
		case 4: // IComponent/connect
		{
			try {
				String receptacle = in.read_string();
				org.omg.CORBA.Object obj = org.omg.CORBA.ObjectHelper.read(in);
				int $result = (int) 0;
				$result = this.connect(receptacle, obj);
				out = $rh.createReply();
				out.write_ulong($result);
			} catch (InvalidName $ex) {
				out = $rh.createExceptionReply();
				InvalidNameHelper.write(out, $ex);
			} catch (InvalidConnection $ex) {
				out = $rh.createExceptionReply();
				InvalidConnectionHelper.write(out, $ex);
			} catch (AlreadyConnected $ex) {
				out = $rh.createExceptionReply();
				AlreadyConnectedHelper.write(out, $ex);
			} catch (ExceededConnectionLimit $ex) {
				out = $rh.createExceptionReply();
				ExceededConnectionLimitHelper.write(out, $ex);
			}
			break;
		}

		case 5: // IComponent/disconnect
		{
			try {
				int id = ConnectionIdHelper.read(in);
				this.disconnect(id);
				out = $rh.createReply();
			} catch (InvalidConnection $ex) {
				out = $rh.createExceptionReply();
				InvalidConnectionHelper.write(out, $ex);
			} catch (NoConnection $ex) {
				out = $rh.createExceptionReply();
				NoConnectionHelper.write(out, $ex);
			}
			break;
		}

		case 6: // IComponent/getConnection
		{
			try {
				int id = ConnectionIdHelper.read(in);
				ConnectionDescription $result = null;
				$result = this.getConnection(id);
				out = $rh.createReply();
				ConnectionDescriptionHelper.write(out, $result);
			} catch (InvalidConnection $ex) {
				out = $rh.createExceptionReply();
				InvalidConnectionHelper.write(out, $ex);
			}
			break;
		}

		case 7: // IComponent/getConnections
		{
			try {
				String receptacle = in.read_string();
				ConnectionDescription $result[] = null;
				$result = this.getConnections(receptacle);
				out = $rh.createReply();
				ConnectionDescriptionsHelper.write(out, $result);
			} catch (InvalidName $ex) {
				out = $rh.createExceptionReply();
				InvalidNameHelper.write(out, $ex);
			}
			break;
		}

		// MetaInterface
		case 8: // IComponent/getFacets
		{
			FacetDescription $result[] = null;
			$result = this.getFacets();
			out = $rh.createReply();
			FacetDescriptionsHelper.write(out, $result);
			break;
		}

		case 9: // IComponent/getFacetsByName
		{
			try {
				String names[] = NameListHelper.read(in);
				FacetDescription $result[] = null;
				$result = this.getFacetsByName(names);
				out = $rh.createReply();
				FacetDescriptionsHelper.write(out, $result);
			} catch (InvalidName $ex) {
				out = $rh.createExceptionReply();
				InvalidNameHelper.write(out, $ex);
			}
			break;
		}

		case 10: // IComponent/getReceptacles
		{
			ReceptacleDescription $result[] = null;
			$result = this.getReceptacles();
			out = $rh.createReply();
			ReceptacleDescriptionsHelper.write(out, $result);
			break;
		}

		case 11: // IComponent/getReceptaclesByName
		{
			try {
				String names[] = NameListHelper.read(in);
				ReceptacleDescription $result[] = null;
				$result = this.getReceptaclesByName(names);
				out = $rh.createReply();
				ReceptacleDescriptionsHelper.write(out, $result);
			} catch (InvalidName $ex) {
				out = $rh.createExceptionReply();
				InvalidNameHelper.write(out, $ex);
			}
			break;
		}

		default:
			throw new org.omg.CORBA.BAD_OPERATION(0,
					org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
		}

		return out;
	} // _invoke

	// Type-specific CORBA::Object operations
	private static String[] __ids = { "IDL:IComponent:1.0" };

	public String[] _all_interfaces(org.omg.PortableServer.POA poa,
			byte[] objectId) {
		return (String[]) __ids.clone();
	}

	public IComponent _this() {
		return IComponentHelper.narrow(super._this_object());
	}

	public IComponent _this(org.omg.CORBA.ORB orb) {
		return IComponentHelper.narrow(super._this_object(orb));
	}

} // class IComponentPOA
