/**
 * IComponent.java . Generated by the IDL-to-Java compiler (portable), version
 * "3.2" from scs.idl Friday, December 9, 2005 9:35:21 PM GMT
 */

public interface IComponent extends IComponentOperations, org.omg.CORBA.Object,
		org.omg.CORBA.portable.IDLEntity {
} // interface IComponent
