/**
 * NoConnection.java . Generated by the IDL-to-Java compiler (portable), version
 * "3.2" from scs.idl Friday, December 9, 2005 9:35:21 PM GMT
 */

public final class NoConnection extends org.omg.CORBA.UserException {

	public NoConnection() {
		super(NoConnectionHelper.id());
	} // ctor

	public NoConnection(String $reason) {
		super(NoConnectionHelper.id() + "  " + $reason);
	} // ctor

} // class NoConnection
