/**
 * NodeLookupOperations.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.2" from deployment.idl Saturday, December 10, 2005 1:24:06 AM GMT
 */

public interface NodeLookupOperations {
	NodeDescription getNode(String name);

	NodeDescription[] getNodes(Property[] props);

	NodeDescription[] getAllNodes();
} // interface NodeLookupOperations
