/**
 * NodeRegisterPOATie.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.2" from deployment.idl Saturday, December 10, 2005 1:24:06 AM GMT
 */

public class NodeRegisterPOATie extends NodeRegisterPOA {

	// Constructors

	public NodeRegisterPOATie(NodeRegisterOperations delegate) {
		this._impl = delegate;
	}

	public NodeRegisterPOATie(NodeRegisterOperations delegate,
			org.omg.PortableServer.POA poa) {
		this._impl = delegate;
		this._poa = poa;
	}

	public NodeRegisterOperations _delegate() {
		return this._impl;
	}

	public void _delegate(NodeRegisterOperations delegate) {
		this._impl = delegate;
	}

	public org.omg.PortableServer.POA _default_POA() {
		if (_poa != null) {
			return _poa;
		} else {
			return super._default_POA();
		}
	}

	public void register(IComponent node, Property[] props) {
		_impl.register(node, props);
	} // register

	public void unregister(IComponent node) throws ComponentNotFound {
		_impl.unregister(node);
	} // unregister

	private NodeRegisterOperations _impl;

	private org.omg.PortableServer.POA _poa;

} // class NodeRegisterPOATie
