/**
 * NodeLookupPOATie.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.2" from deployment.idl Saturday, December 10, 2005 1:24:06 AM GMT
 */

public class NodeLookupPOATie extends NodeLookupPOA {

	// Constructors

	public NodeLookupPOATie(NodeLookupOperations delegate) {
		this._impl = delegate;
	}

	public NodeLookupPOATie(NodeLookupOperations delegate,
			org.omg.PortableServer.POA poa) {
		this._impl = delegate;
		this._poa = poa;
	}

	public NodeLookupOperations _delegate() {
		return this._impl;
	}

	public void _delegate(NodeLookupOperations delegate) {
		this._impl = delegate;
	}

	public org.omg.PortableServer.POA _default_POA() {
		if (_poa != null) {
			return _poa;
		} else {
			return super._default_POA();
		}
	}

	public NodeDescription getNode(String name) {
		return _impl.getNode(name);
	} // getNode

	public NodeDescription[] getNodes(Property[] props) {
		return _impl.getNodes(props);
	} // getNodes

	public NodeDescription[] getAllNodes() {
		return _impl.getAllNodes();
	} // getAllNodes

	private NodeLookupOperations _impl;

	private org.omg.PortableServer.POA _poa;

} // class NodeLookupPOATie
