/**
 * StartupFailed.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.2" from scs.idl Friday, December 9, 2005 9:35:21 PM GMT
 */

public final class StartupFailed extends org.omg.CORBA.UserException {

	public StartupFailed() {
		super(StartupFailedHelper.id());
	} // ctor

	public StartupFailed(String $reason) {
		super(StartupFailedHelper.id() + "  " + $reason);
	} // ctor

} // class StartupFailed
