package uff.ic.biblioteca.model;
// Generated Oct 3, 2013 6:26:57 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

    private long id;
    private Tipo tipo;
    private String nome;
    private Long telefone;
    private Long celular;
    private String email;
    private Long cpf;
    private String logradouro;
    private String complemento;
    private String bairro;
    private String cidade;
    private Long cep;
    private Date admissao;
    private Date cancelamento;
    private Set operacaos = new HashSet(0);
    private Set logins = new HashSet(0);

    public Usuario() {
    }

    public Usuario(long id, Tipo tipo, String nome) {
        this.id = id;
        this.tipo = tipo;
        this.nome = nome;
    }

    public Usuario(long id, Tipo tipo, String nome, Long telefone, Long celular, String email, Long cpf, String logradouro, String complemento, String bairro, String cidade, Long cep, Date admissao, Date cancelamento, Set operacaos, Set logins) {
        this.id = id;
        this.tipo = tipo;
        this.nome = nome;
        this.telefone = telefone;
        this.celular = celular;
        this.email = email;
        this.cpf = cpf;
        this.logradouro = logradouro;
        this.complemento = complemento;
        this.bairro = bairro;
        this.cidade = cidade;
        this.cep = cep;
        this.admissao = admissao;
        this.cancelamento = cancelamento;
        this.operacaos = operacaos;
        this.logins = logins;
    }

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Tipo getTipo() {
        return this.tipo;
    }

    public void setTipo(Tipo tipo) {
        this.tipo = tipo;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public Long getTelefone() {
        return this.telefone;
    }

    public void setTelefone(Long telefone) {
        this.telefone = telefone;
    }

    public Long getCelular() {
        return this.celular;
    }

    public void setCelular(Long celular) {
        this.celular = celular;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Long getCpf() {
        return this.cpf;
    }

    public void setCpf(Long cpf) {
        this.cpf = cpf;
    }

    public String getLogradouro() {
        return this.logradouro;
    }

    public void setLogradouro(String logradouro) {
        this.logradouro = logradouro;
    }

    public String getComplemento() {
        return this.complemento;
    }

    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }

    public String getBairro() {
        return this.bairro;
    }

    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    public String getCidade() {
        return this.cidade;
    }

    public void setCidade(String cidade) {
        this.cidade = cidade;
    }

    public Long getCep() {
        return this.cep;
    }

    public void setCep(Long cep) {
        this.cep = cep;
    }

    public Date getAdmissao() {
        return this.admissao;
    }

    public void setAdmissao(Date admissao) {
        this.admissao = admissao;
    }

    public Date getCancelamento() {
        return this.cancelamento;
    }

    public void setCancelamento(Date cancelamento) {
        this.cancelamento = cancelamento;
    }

    public Set getOperacaos() {
        return this.operacaos;
    }

    public void setOperacaos(Set operacaos) {
        this.operacaos = operacaos;
    }

    public Set getLogins() {
        return this.logins;
    }

    public void setLogins(Set logins) {
        this.logins = logins;
    }
}
