package uff.ic.corba.testes.javaORB.StockObjects;

/**
 * StockObjects/UnknownHolder.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.1" from stock.idl S�bado, 17 de Setembro de 2005
 * 14h14min39s BRT
 */

public final class UnknownHolder implements org.omg.CORBA.portable.Streamable {
	public uff.ic.corba.testes.javaORB.StockObjects.Unknown value = null;

	public UnknownHolder() {
	}

	public UnknownHolder(uff.ic.corba.testes.javaORB.StockObjects.Unknown initialValue) {
		value = initialValue;
	}

	public void _read(org.omg.CORBA.portable.InputStream i) {
		value = uff.ic.corba.testes.javaORB.StockObjects.UnknownHelper.read(i);
	}

	public void _write(org.omg.CORBA.portable.OutputStream o) {
		uff.ic.corba.testes.javaORB.StockObjects.UnknownHelper.write(o, value);
	}

	public org.omg.CORBA.TypeCode _type() {
		return uff.ic.corba.testes.javaORB.StockObjects.UnknownHelper.type();
	}

}
