/* Generated by Together */

package br.pucrio.inf.geocat;

import org.xml.sax.InputSource;

import br.pucrio.inf.catfwk.model.Builder;
import br.pucrio.inf.catfwk.model.Parser;

/**
 * @author Luiz André
 * @version 1.0
 * @since 1.0
 * @alias GeoTIFFParser*/
public class GeoTIFFParser extends Parser {

	public GeoTIFFParser(Builder builder) {
		super(builder);
	}

	public MetadataElement[] parse(InputSource source) {
		// TODO Auto-generated method stub
		return null;
	}
}
