package ic.tcc00175.biblioteca.model;
// Generated Oct 3, 2013 6:26:57 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Exemplar generated by hbm2java
 */
public class Exemplar implements java.io.Serializable {

    private ExemplarId id;
    private Material material;
    private String desc;
    private Set emprestimos = new HashSet(0);

    public Exemplar() {
    }

    public Exemplar(ExemplarId id, Material material) {
        this.id = id;
        this.material = material;
    }

    public Exemplar(ExemplarId id, Material material, String desc, Set emprestimos) {
        this.id = id;
        this.material = material;
        this.desc = desc;
        this.emprestimos = emprestimos;
    }

    public ExemplarId getId() {
        return this.id;
    }

    public void setId(ExemplarId id) {
        this.id = id;
    }

    public Material getMaterial() {
        return this.material;
    }

    public void setMaterial(Material material) {
        this.material = material;
    }

    public String getDesc() {
        return this.desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public Set getEmprestimos() {
        return this.emprestimos;
    }

    public void setEmprestimos(Set emprestimos) {
        this.emprestimos = emprestimos;
    }
}
