/* Generated by Together */

package br.pucrio.inf.catfwk.appmodel;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.Serializable;

/**
 * @version 1.0
 * @since 1.0
 * @author Luiz André
 * @alias Document*/
public abstract interface Document extends Serializable {

	/**
	 * @version 1.0
	 * @since 1.0
	 * @return nome do arquivo no qual é serializado o documento
	 */
	public abstract String getFilename();

	/**
	 * @version 1.0
	 * @since 1.0
	 * @param filename
	 *            The filename to set.
	 */
	public abstract void setFilename(String filename);

	/**
	 * Abre o arquivo no qual é serializado o documento
	 * 
	 * @version 1.0
	 * @since 1.0
	 * @exception FileNotFoundException
	 */
	public abstract void open() throws FileNotFoundException;

	/**
	 * Fecha o arquivo no qual é serializado o documento
	 * 
	 * @version 1.0
	 * @since 1.0
	 * @exception IOException
	 */
	public abstract void close() throws IOException;

	/**
	 * Serializa o documento.
	 * 
	 * @version 1.0
	 * @since 1.0
	 * @exception IOExcpetion
	 */
	public abstract void save() throws IOException;

} // @jve:decl-index=0:visual-constraint="10,10"
