/* Generated by Together */

package br.pucrio.inf.catfwk.appmodel;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;

import br.pucrio.inf.catfwk.model.CataloguingProcess;
import br.pucrio.inf.lib.observer.SubjectImpl;

/**
 * @version 1.0
 * @since 1.0
 * @author Luiz André
 * @alias WspImpl*/
public class WspImpl extends SubjectImpl implements Document, Workspace {
	public WspImpl() {
		// TODO
	}

	private static final long serialVersionUID = -3889924298455185047L;

	public boolean addProcess(CataloguingProcess process) {
		boolean result = processList.add(process);
		notifyObservers();
		return result;
	}

	/**
	 * @return Returns the processList.
	 */
	public CataloguingProcess[] getProcessList() {
		return (CataloguingProcess[]) processList
				.toArray(new CataloguingProcess[0]);
	}

	public boolean removeProcess(CataloguingProcess process) {
		boolean result = processList.remove(process);
		notifyObservers();
		return result;
	}

	/**
	 * @return Returns the filename.
	 */
	public String getFilename() {
		return filename;
	}

	private transient String filename = null;

	protected transient FileInputStream in = null;

	/**
	 * @param filename
	 *            The filename to set.
	 */
	public void setFilename(String filename) {
		this.filename = filename;
	}

	public void open() throws FileNotFoundException {
		File file = new File(getFilename());
		if (file.exists())
			in = new FileInputStream(getFilename());
	}

	public void close() throws IOException {
		if (in != null)
			in.close();
	}

	public void save() throws IOException {
		ObjectOutputStream s = null;
		FileOutputStream out = null;
		if (in != null)
			in.close();
		out = new FileOutputStream(getFilename());
		s = new ObjectOutputStream(out);
		s.writeObject(this);
		s.flush();
		s.close();
		open();
	}

	/**
	 * @link aggregationByValue
	 * @associates <{CataloguingProcess}>
	 * @supplierCardinality 0..**/
	private ArrayList processList = new ArrayList();
}
