package lleme.corba.testes.javaORB.StockObjects;

/**
 * StockObjects/_StockStub.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.1" from stock.idl Sábado, 17 de Setembro de 2005
 * 14h14min39s BRT
 */

public class _StockStub extends org.omg.CORBA.portable.ObjectImpl implements
		lleme.corba.testes.javaORB.StockObjects.Stock {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7417152042130721218L;

	// Returns the current stock quote.
	public lleme.corba.testes.javaORB.StockObjects.Quote get_quote()
			throws lleme.corba.testes.javaORB.StockObjects.Unknown {
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request("get_quote",
					true);
			$in = _invoke($out);
			lleme.corba.testes.javaORB.StockObjects.Quote $result = lleme.corba.testes.javaORB.StockObjects.QuoteHelper
					.read($in);
			return $result;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream();
			String _id = $ex.getId();
			if (_id.equals("IDL:StockObjects/Unknown:1.0"))
				throw lleme.corba.testes.javaORB.StockObjects.UnknownHelper.read($in);
			throw new org.omg.CORBA.MARSHAL(_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			return get_quote();
		} finally {
			_releaseReply($in);
		}
	} // get_quote

	// *** put your operation for setting the quote here
	public void set_quote(lleme.corba.testes.javaORB.StockObjects.Quote stock_quote) {
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request("set_quote",
					true);
			lleme.corba.testes.javaORB.StockObjects.QuoteHelper.write($out, stock_quote);
			$in = _invoke($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream();
			String _id = $ex.getId();
			throw new org.omg.CORBA.MARSHAL(_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			set_quote(stock_quote);
		} finally {
			_releaseReply($in);
		}
	} // set_quote

	// Provides the stock description, e.g. company name.
	public String description() {
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request(
					"_get_description", true);
			$in = _invoke($out);
			String $result = $in.read_string();
			return $result;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream();
			String _id = $ex.getId();
			throw new org.omg.CORBA.MARSHAL(_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			return description();
		} finally {
			_releaseReply($in);
		}
	} // description

	// Type-specific CORBA::Object operations
	private static String[] __ids = { "IDL:StockObjects/Stock:1.0" };

	public String[] _ids() {
		return __ids.clone();
	}

	private void readObject(java.io.ObjectInputStream s)
			throws java.io.IOException {
		String str = s.readUTF();
		String[] args = null;
		java.util.Properties props = null;
		org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init(args, props)
				.string_to_object(str);
		org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)
				._get_delegate();
		_set_delegate(delegate);
	}

	private void writeObject(java.io.ObjectOutputStream s)
			throws java.io.IOException {
		String[] args = null;
		java.util.Properties props = null;
		String str = org.omg.CORBA.ORB.init(args, props).object_to_string(this);
		s.writeUTF(str);
	}
} // class _StockStub
