package lleme.corba.testes.javaORB.StockObjects;

/**
 * StockObjects/_StockImplBase.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.1" from stock.idl Sábado, 17 de Setembro de 2005
 * 14h14min39s BRT
 */

public abstract class _StockImplBase extends org.omg.CORBA.portable.ObjectImpl
		implements lleme.corba.testes.javaORB.StockObjects.Stock,
		org.omg.CORBA.portable.InvokeHandler {

	// Constructors
	public _StockImplBase() {
	}

	private static java.util.Hashtable _methods = new java.util.Hashtable();
	static {
		_methods.put("get_quote", new java.lang.Integer(0));
		_methods.put("set_quote", new java.lang.Integer(1));
		_methods.put("_get_description", new java.lang.Integer(2));
	}

	public org.omg.CORBA.portable.OutputStream _invoke(String $method,
			org.omg.CORBA.portable.InputStream in,
			org.omg.CORBA.portable.ResponseHandler $rh) {
		org.omg.CORBA.portable.OutputStream out = null;
		java.lang.Integer __method = (java.lang.Integer) _methods.get($method);
		if (__method == null)
			throw new org.omg.CORBA.BAD_OPERATION(0,
					org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

		switch (__method.intValue()) {

		// Returns the current stock quote.
		case 0: // StockObjects/Stock/get_quote
		{
			try {
				lleme.corba.testes.javaORB.StockObjects.Quote $result = null;
				$result = this.get_quote();
				out = $rh.createReply();
				lleme.corba.testes.javaORB.StockObjects.QuoteHelper.write(out, $result);
			} catch (lleme.corba.testes.javaORB.StockObjects.Unknown $ex) {
				out = $rh.createExceptionReply();
				lleme.corba.testes.javaORB.StockObjects.UnknownHelper.write(out, $ex);
			}
			break;
		}

		// *** put your operation for setting the quote here
		case 1: // StockObjects/Stock/set_quote
		{
			lleme.corba.testes.javaORB.StockObjects.Quote stock_quote = lleme.corba.testes.javaORB.StockObjects.QuoteHelper
					.read(in);
			this.set_quote(stock_quote);
			out = $rh.createReply();
			break;
		}

		// Provides the stock description, e.g. company name.
		case 2: // StockObjects/Stock/_get_description
		{
			String $result = null;
			$result = this.description();
			out = $rh.createReply();
			out.write_string($result);
			break;
		}

		default:
			throw new org.omg.CORBA.BAD_OPERATION(0,
					org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
		}

		return out;
	} // _invoke

	// Type-specific CORBA::Object operations
	private static String[] __ids = { "IDL:StockObjects/Stock:1.0" };

	public String[] _ids() {
		return __ids.clone();
	}

} // class _StockImplBase
