package lleme.corba.testes.javaORB.StockObjects;

/**
 * StockObjects/Quote.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.1" from stock.idl Sábado, 17 de Setembro de 2005 14h14min39s BRT
 */

public final class Quote implements org.omg.CORBA.portable.IDLEntity {
	/**
	 * 
	 */
	private static final long serialVersionUID = 3545338636587438254L;

	public String symbol = null;

	// The stock symbol of this quote.
	public long at_time = 0;

	// Time at which the price was updated.
	public double price = 0;

	// The current price of the stock.
	public int volume = 0;

	public Quote() {
	} // ctor

	public Quote(String _symbol, long _at_time, double _price, int _volume) {
		symbol = _symbol;
		at_time = _at_time;
		price = _price;
		volume = _volume;
	} // ctor

} // class Quote
