package lleme.corba.testes.javaORB.StockObjects;

/**
 * StockObjects/Stock.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.1" from stock.idl Sábado, 17 de Setembro de 2005 14h14min39s BRT
 */

public interface Stock extends StockOperations, org.omg.CORBA.Object,
		org.omg.CORBA.portable.IDLEntity {
} // interface Stock
