package lleme.corba.testes.javaORB.StockObjects;

/**
 * StockObjects/StockOperations.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.1" from stock.idl Sábado, 17 de Setembro de 2005
 * 14h14min39s BRT
 */

public interface StockOperations {

	// Returns the current stock quote.
	lleme.corba.testes.javaORB.StockObjects.Quote get_quote()
			throws lleme.corba.testes.javaORB.StockObjects.Unknown;

	// *** put your operation for setting the quote here
	void set_quote(lleme.corba.testes.javaORB.StockObjects.Quote stock_quote);

	// Provides the stock description, e.g. company name.
	String description();
} // interface StockOperations
