package lleme.corba.testes.javaORB.StockObjects;

/**
 * StockObjects/Stock_Tie.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.1" from stock.idl Sábado, 17 de Setembro de 2005
 * 14h14min39s BRT
 */

public class Stock_Tie extends _StockImplBase {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3313418419611912614L;

	// Constructors
	public Stock_Tie() {
	}

	public Stock_Tie(lleme.corba.testes.javaORB.StockObjects.StockOperations impl) {
		super();
		_impl = impl;
	}

	// Returns the current stock quote.
	public lleme.corba.testes.javaORB.StockObjects.Quote get_quote()
			throws lleme.corba.testes.javaORB.StockObjects.Unknown {
		return _impl.get_quote();
	} // get_quote

	// *** put your operation for setting the quote here
	public void set_quote(lleme.corba.testes.javaORB.StockObjects.Quote stock_quote) {
		_impl.set_quote(stock_quote);
	} // set_quote

	// Provides the stock description, e.g. company name.
	public String description() {
		return _impl.description();
	} // description

	private lleme.corba.testes.javaORB.StockObjects.StockOperations _impl;

} // class Stock_Tie
