package lleme.corba.testes.javaORB.StockObjects;

/**
 * StockObjects/StockHolder.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.1" from stock.idl Sábado, 17 de Setembro de 2005
 * 14h14min39s BRT
 */

public final class StockHolder implements org.omg.CORBA.portable.Streamable {
	public lleme.corba.testes.javaORB.StockObjects.Stock value = null;

	public StockHolder() {
	}

	public StockHolder(lleme.corba.testes.javaORB.StockObjects.Stock initialValue) {
		value = initialValue;
	}

	public void _read(org.omg.CORBA.portable.InputStream i) {
		value = lleme.corba.testes.javaORB.StockObjects.StockHelper.read(i);
	}

	public void _write(org.omg.CORBA.portable.OutputStream o) {
		lleme.corba.testes.javaORB.StockObjects.StockHelper.write(o, value);
	}

	public org.omg.CORBA.TypeCode _type() {
		return lleme.corba.testes.javaORB.StockObjects.StockHelper.type();
	}

}
