package uff.ic.lleme.letstalk.cbobjs.corbaObjects.letstalk;

import uff.ic.lleme.letstalk.cbobjs.corbaObjects.scs.AlreadyConnected;
import uff.ic.lleme.letstalk.cbobjs.corbaObjects.scs.ExceededConnectionLimit;
import uff.ic.lleme.letstalk.cbobjs.corbaObjects.scs.InvalidConnection;
import uff.ic.lleme.letstalk.cbobjs.corbaObjects.scs.NoConnection;

/**
 * corbaObjects/letstalk/UserFacetOperations.java . Generated by the IDL-to-Java
 * compiler (portable), version "3.2" from letstalk.idl Sexta-feira, 9 de
 * Dezembro de 2005 18h26min29s BRST
 */
public interface UserFacetOperations {

    void subscribe(String login, String password)
            throws uff.ic.lleme.letstalk.cbobjs.corbaObjects.letstalk.InvalidSubscriptionValues, 
            uff.ic.lleme.letstalk.cbobjs.corbaObjects.scs.InternalError;

    int connect(String login, String password, org.omg.CORBA.Object host)
            throws uff.ic.lleme.letstalk.cbobjs.corbaObjects.scs.InvalidName,
            InvalidConnection,
            AlreadyConnected,
            ExceededConnectionLimit,
            uff.ic.lleme.letstalk.cbobjs.corbaObjects.scs.InternalError;

    void disconnect(String login) throws InvalidConnection,
            NoConnection,
            uff.ic.lleme.letstalk.cbobjs.corbaObjects.scs.InternalError;

    String[] listUsers() throws uff.ic.lleme.letstalk.cbobjs.corbaObjects.scs.InternalError;
} // interface UserFacetOperations
