package uff.ic.biblioteca.model;
// Generated Oct 3, 2013 6:26:57 PM by Hibernate Tools 3.2.1.GA

/**
 * Cd generated by hbm2java
 */
public class Cd implements java.io.Serializable {

    private long materialCodigo;
    private Material material;
    private String autores;
    private Long ano;

    public Cd() {
    }

    public Cd(long materialCodigo, Material material) {
        this.materialCodigo = materialCodigo;
        this.material = material;
    }

    public Cd(long materialCodigo, Material material, String autores, Long ano) {
        this.materialCodigo = materialCodigo;
        this.material = material;
        this.autores = autores;
        this.ano = ano;
    }

    public long getMaterialCodigo() {
        return this.materialCodigo;
    }

    public void setMaterialCodigo(long materialCodigo) {
        this.materialCodigo = materialCodigo;
    }

    public Material getMaterial() {
        return this.material;
    }

    public void setMaterial(Material material) {
        this.material = material;
    }

    public String getAutores() {
        return this.autores;
    }

    public void setAutores(String autores) {
        this.autores = autores;
    }

    public Long getAno() {
        return this.ano;
    }

    public void setAno(Long ano) {
        this.ano = ano;
    }
}
