package uff.ic.biblioteca.model;
// Generated Oct 3, 2013 6:26:57 PM by Hibernate Tools 3.2.1.GA

/**
 * ExemplarId generated by hbm2java
 */
public class ExemplarId implements java.io.Serializable {

    private long codigo;
    private long num;

    public ExemplarId() {
    }

    public ExemplarId(long codigo, long num) {
        this.codigo = codigo;
        this.num = num;
    }

    public long getCodigo() {
        return this.codigo;
    }

    public void setCodigo(long codigo) {
        this.codigo = codigo;
    }

    public long getNum() {
        return this.num;
    }

    public void setNum(long num) {
        this.num = num;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof ExemplarId)) {
            return false;
        }
        ExemplarId castOther = (ExemplarId) other;

        return (this.getCodigo() == castOther.getCodigo())
                && (this.getNum() == castOther.getNum());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (int) this.getCodigo();
        result = 37 * result + (int) this.getNum();
        return result;
    }
}
