package uff.ic.biblioteca.model;
// Generated Oct 3, 2013 6:26:57 PM by Hibernate Tools 3.2.1.GA

/**
 * Reserva generated by hbm2java
 */
public class Reserva implements java.io.Serializable {

    private long operacaoNumero;
    private Operacao operacao;
    private Livro livro;
    private String obs;

    public Reserva() {
    }

    public Reserva(long operacaoNumero, Operacao operacao, Livro livro) {
        this.operacaoNumero = operacaoNumero;
        this.operacao = operacao;
        this.livro = livro;
    }

    public Reserva(long operacaoNumero, Operacao operacao, Livro livro, String obs) {
        this.operacaoNumero = operacaoNumero;
        this.operacao = operacao;
        this.livro = livro;
        this.obs = obs;
    }

    public long getOperacaoNumero() {
        return this.operacaoNumero;
    }

    public void setOperacaoNumero(long operacaoNumero) {
        this.operacaoNumero = operacaoNumero;
    }

    public Operacao getOperacao() {
        return this.operacao;
    }

    public void setOperacao(Operacao operacao) {
        this.operacao = operacao;
    }

    public Livro getLivro() {
        return this.livro;
    }

    public void setLivro(Livro livro) {
        this.livro = livro;
    }

    public String getObs() {
        return this.obs;
    }

    public void setObs(String obs) {
        this.obs = obs;
    }
}
