/* Generated by Together */

package br.pucrio.inf.catfwk.model;

/**
 * @author Luiz André
 * @version 1.0
 * @since 1.0
 * @alias Builder
 * @stereotype abstract*/
abstract public class Builder {

	public Builder() {
		// TODO
	}

	abstract public void build(Object metadataElements)
			throws InvalidDatasetDescException, NumberFormatException;

	/**
	 * @associates <{br.pucrio.inf.catfwk.model.DatasetDescription}>
	 * 
	 * @return*/
	abstract public DatasetDescription getDatasetDescription();
}
