/* Generated by Together */

package br.pucrio.inf.catfwk.model;

import java.io.Serializable;

/**
 * @author Luiz André
 * @version 1.0
 * @since 1.0
 * @alias DatasetDescription*/
abstract public class DatasetDescription implements Serializable {

	/**
	 * @return Returns the identifier.
	 */
	public String getIdentifier() {
		return identifier;
	}

	/**
	 * @param identifier
	 *            The identifier to set.
	 */
	public void setIdentifier(String identifier) {
		this.identifier = identifier;
	}

	/**
	 * @return Returns the uri.
	 */
	public String getUri() {
		return uri;
	}

	/**
	 * @param uri
	 *            The uri to set.
	 */
	public void setUri(String uri) {
		this.uri = uri;
	}

	/**
	 * @return Returns the failReason.
	 */
	public String getFailReason() {
		return failReason;
	}

	/**
	 * @param failReason
	 *            The failReason to set.
	 */
	public void setFailReason(String failReason) {
		this.failReason = failReason;
	}

	/**
	 * @return Returns the status.
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * @param status
	 *            The status to set.
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	public String toString() {
		return uri + " (" + getStatus()
				+ (getFailReason() == null ? "" : " - " + getFailReason())
				+ ")";
	}

	public abstract void aggregateDescription(
			DatasetDescription datasetDescription);

	private String identifier = null;

	private String uri = null;

	private String status = null;

	private String failReason = null;

}
