/* Generated by Together */

package br.pucrio.inf.catfwk.model;

import java.io.IOException;
import java.util.Collection;
import java.util.HashMap;

import javax.xml.parsers.ParserConfigurationException;

import org.xml.sax.SAXException;

/**
 * @author Luiz André
 * @version 1.0
 * @since 1.0*/
public class MemoryCatalog extends Catalog {
	/**
	 * @link aggregation
	 * @associates <{Resource}>
	 * @supplierCardinality 0..*
	 */
	private HashMap descriptions = null;

	public MemoryCatalog() {
		super("");
	}

	public synchronized DatasetDescription put(
			DatasetDescription datasetDescription) {
		load();
		DatasetDescription _datasetDEscription = (DatasetDescription) descriptions
				.put(datasetDescription.getUri(), datasetDescription);
		return _datasetDEscription;
	}

	public synchronized DatasetDescription remove(
			DatasetDescription datasetDescription) {
		load();
		DatasetDescription _datasetDescription = (DatasetDescription) descriptions
				.remove(datasetDescription.getUri());
		return _datasetDescription;
	}

	public synchronized DatasetDescription get(Object key) {
		load();
		return (DatasetDescription) descriptions.get(key);
	}

	public synchronized boolean contains(String filename) {
		load();
		return descriptions.containsKey(filename);
	}

	public int size() {
		load();
		return descriptions.size();
	}

	public synchronized void load() {
		if (descriptions == null)
			descriptions = new HashMap();
	}

	public synchronized void connect() {
		// TODO Auto-generated method stub

	}

	public synchronized void disconnect() {
		// TODO Auto-generated method stub

	}

	public synchronized Collection values() {
		return descriptions.values();
	}

	public synchronized void exportXML() {
		// TODO Auto-generated method stub

	}

	public DatasetDescription getDesciption(DatasetDescription datsetDescription) {
		// TODO Auto-generated method stub
		return null;
	}

	public Builder getBuilder() {
		// TODO Auto-generated method stub
		return null;
	}

	public DatasetDescription getDescription(Object obj) throws IOException, InvalidDatasetDescException, ParserConfigurationException, SAXException {
		// TODO Auto-generated method stub
		return null;
	}
}
