/* Generated by Together */

package lleme.letstalk.node;

import java.io.IOException;

import javax.xml.parsers.ParserConfigurationException;

import org.xml.sax.InputSource;
import org.xml.sax.SAXException;
import org.xml.sax.helpers.DefaultHandler;

/**
 * @author Luiz André
 * @version 1.0
 * @since 1.0
 */
abstract public class Reader extends DefaultHandler {
	public Reader(Builder builder) {
		this.builder = builder;
	}

	public abstract MetadataElement[] parse(InputSource source)
			throws ParserConfigurationException, SAXException, IOException,
			InvalidSourceContentException;

	/**
	 * @return Returns the builder.
	 */
	public Builder getBuilder() {
		return builder;
	}

	/**
	 * @param builder
	 *            The builder to set.
	 */
	public void setBuilder(Builder builder) {
		this.builder = builder;
	}

	/** @associates <{Builder}> */
	private Builder builder = null;
}
