/**
 * ComponentDescriptionSeqHelper.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from deployment.idl Saturday, December 10, 2005
 * 1:24:06 AM GMT
 */

abstract public class ComponentDescriptionSeqHelper {
	private static String _id = "IDL:ComponentDescriptionSeq:1.0";

	public static void insert(org.omg.CORBA.Any a, ComponentDescription[] that) {
		org.omg.CORBA.portable.OutputStream out = a.create_output_stream();
		a.type(type());
		write(out, that);
		a.read_value(out.create_input_stream(), type());
	}

	public static ComponentDescription[] extract(org.omg.CORBA.Any a) {
		return read(a.create_input_stream());
	}

	private static org.omg.CORBA.TypeCode __typeCode = null;

	synchronized public static org.omg.CORBA.TypeCode type() {
		if (__typeCode == null) {
			__typeCode = ComponentDescriptionHelper.type();
			__typeCode = org.omg.CORBA.ORB.init().create_sequence_tc(0,
					__typeCode);
			__typeCode = org.omg.CORBA.ORB.init().create_alias_tc(
					ComponentDescriptionSeqHelper.id(),
					"ComponentDescriptionSeq", __typeCode);
		}
		return __typeCode;
	}

	public static String id() {
		return _id;
	}

	public static ComponentDescription[] read(
			org.omg.CORBA.portable.InputStream istream) {
		ComponentDescription value[] = null;
		int _len0 = istream.read_long();
		value = new ComponentDescription[_len0];
		for (int _o1 = 0; _o1 < value.length; ++_o1)
			value[_o1] = ComponentDescriptionHelper.read(istream);
		return value;
	}

	public static void write(org.omg.CORBA.portable.OutputStream ostream,
			ComponentDescription[] value) {
		ostream.write_long(value.length);
		for (int _i0 = 0; _i0 < value.length; ++_i0)
			ComponentDescriptionHelper.write(ostream, value[_i0]);
	}

}
