/**
 * ComponentCollectionPOATie.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from deployment.idl Saturday, December 10, 2005
 * 1:24:06 AM GMT
 */

public class ComponentCollectionPOATie extends ComponentCollectionPOA {

	// Constructors

	public ComponentCollectionPOATie(ComponentCollectionOperations delegate) {
		this._impl = delegate;
	}

	public ComponentCollectionPOATie(ComponentCollectionOperations delegate,
			org.omg.PortableServer.POA poa) {
		this._impl = delegate;
		this._poa = poa;
	}

	public ComponentCollectionOperations _delegate() {
		return this._impl;
	}

	public void _delegate(ComponentCollectionOperations delegate) {
		this._impl = delegate;
	}

	public org.omg.PortableServer.POA _default_POA() {
		if (_poa != null) {
			return _poa;
		} else {
			return super._default_POA();
		}
	}

	public ComponentHandle[] getComponents() {
		return _impl.getComponents();
	} // getComponents

	private ComponentCollectionOperations _impl;

	private org.omg.PortableServer.POA _poa;

} // class ComponentCollectionPOATie
