/**
 * ContainerDescription.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.2" from deployment.idl Saturday, December 10, 2005 1:24:06 AM GMT
 */

public final class ContainerDescription implements
		org.omg.CORBA.portable.IDLEntity {
	public IComponent container = null;

	public String container_name = null;

	public IComponent execution_node = null;

	public ContainerDescription() {
	} // ctor

	public ContainerDescription(IComponent _container, String _container_name,
			IComponent _execution_node) {
		container = _container;
		container_name = _container_name;
		execution_node = _execution_node;
	} // ctor

} // class ContainerDescription
