/**
 * FacetDescriptionsHolder.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from scs.idl Friday, December 9, 2005 9:35:21 PM
 * GMT
 */

public final class FacetDescriptionsHolder implements
		org.omg.CORBA.portable.Streamable {
	public FacetDescription value[] = null;

	public FacetDescriptionsHolder() {
	}

	public FacetDescriptionsHolder(FacetDescription[] initialValue) {
		value = initialValue;
	}

	public void _read(org.omg.CORBA.portable.InputStream i) {
		value = FacetDescriptionsHelper.read(i);
	}

	public void _write(org.omg.CORBA.portable.OutputStream o) {
		FacetDescriptionsHelper.write(o, value);
	}

	public org.omg.CORBA.TypeCode _type() {
		return FacetDescriptionsHelper.type();
	}

}
