/**
 * NodeDescription.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.2" from deployment.idl Saturday, December 10, 2005 1:24:06 AM GMT
 */

public final class NodeDescription implements org.omg.CORBA.portable.IDLEntity {
	public IComponent node = null;

	public Property props[] = null;

	public NodeDescription() {
	} // ctor

	public NodeDescription(IComponent _node, Property[] _props) {
		node = _node;
		props = _props;
	} // ctor

} // class NodeDescription
