/**
 * ReceptacleDescription.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from scs.idl Friday, December 9, 2005 9:35:21 PM
 * GMT
 */

public final class ReceptacleDescription implements
		org.omg.CORBA.portable.IDLEntity {
	public String name = null;

	public String interface_name = null;

	public boolean is_multiplex = false;

	public ConnectionDescription connections[] = null;

	public ReceptacleDescription() {
	} // ctor

	public ReceptacleDescription(String _name, String _interface_name,
			boolean _is_multiplex, ConnectionDescription[] _connections) {
		name = _name;
		interface_name = _interface_name;
		is_multiplex = _is_multiplex;
		connections = _connections;
	} // ctor

} // class ReceptacleDescription
