/**
 * SCSPOA.java . Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from scs.idl Friday, December 9, 2005 9:35:21 PM GMT
 */

public abstract class SCSPOA extends org.omg.PortableServer.Servant implements
		SCSOperations, org.omg.CORBA.portable.InvokeHandler {

	// Constructors

	private static java.util.Hashtable _methods = new java.util.Hashtable();
	static {
		_methods.put("getIComponent", new java.lang.Integer(0));
		_methods.put("releaseIComponent", new java.lang.Integer(1));
	}

	public org.omg.CORBA.portable.OutputStream _invoke(String $method,
			org.omg.CORBA.portable.InputStream in,
			org.omg.CORBA.portable.ResponseHandler $rh) {
		org.omg.CORBA.portable.OutputStream out = null;
		java.lang.Integer __method = (java.lang.Integer) _methods.get($method);
		if (__method == null)
			throw new org.omg.CORBA.BAD_OPERATION(0,
					org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

		switch (__method.intValue()) {
		case 0: // SCS/getIComponent
		{
			try {
				String className = in.read_string();
				int instance_id = in.read_ulong();
				IComponent $result = null;
				$result = this.getIComponent(className, instance_id);
				out = $rh.createReply();
				IComponentHelper.write(out, $result);
			} catch (InternalError $ex) {
				out = $rh.createExceptionReply();
				InternalErrorHelper.write(out, $ex);
			}
			break;
		}

		case 1: // SCS/releaseIComponent
		{
			String className = in.read_string();
			int instance_id = in.read_ulong();
			IComponent $result = null;
			$result = this.releaseIComponent(className, instance_id);
			out = $rh.createReply();
			IComponentHelper.write(out, $result);
			break;
		}

		default:
			throw new org.omg.CORBA.BAD_OPERATION(0,
					org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
		}

		return out;
	} // _invoke

	// Type-specific CORBA::Object operations
	private static String[] __ids = { "IDL:SCS:1.0" };

	public String[] _all_interfaces(org.omg.PortableServer.POA poa,
			byte[] objectId) {
		return (String[]) __ids.clone();
	}

	public SCS _this() {
		return SCSHelper.narrow(super._this_object());
	}

	public SCS _this(org.omg.CORBA.ORB orb) {
		return SCSHelper.narrow(super._this_object(orb));
	}

} // class SCSPOA
