/**
 * StartupFailedHolder.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.2" from scs.idl Friday, December 9, 2005 9:35:21 PM GMT
 */

public final class StartupFailedHolder implements
		org.omg.CORBA.portable.Streamable {
	public StartupFailed value = null;

	public StartupFailedHolder() {
	}

	public StartupFailedHolder(StartupFailed initialValue) {
		value = initialValue;
	}

	public void _read(org.omg.CORBA.portable.InputStream i) {
		value = StartupFailedHelper.read(i);
	}

	public void _write(org.omg.CORBA.portable.OutputStream o) {
		StartupFailedHelper.write(o, value);
	}

	public org.omg.CORBA.TypeCode _type() {
		return StartupFailedHelper.type();
	}

}
