DROP TABLE imdb.PARTICIPA_DE;
DROP TABLE imdb.CRITICA;
DROP TABLE imdb.PROFISSIONAL;
DROP TABLE imdb.TIPO_PARTICIPACAO;
DROP TABLE imdb.SOBRE;
DROP TABLE imdb.NOTICIA;
DROP TABLE imdb.COMENTARIO;
DROP TABLE imdb.FILME;
DROP TABLE imdb.GENERO;
DROP TABLE imdb.ASSUNTO;
DROP TABLE imdb.TIPO_ASSUNTO;
DROP TABLE imdb.USUARIO;
DROP TABLE imdb.TIPO_USUARIO;

CREATE TABLE imdb.TIPO_USUARIO(
	ID INTEGER PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL
);

CREATE TABLE imdb.USUARIO(
	ID INTEGER PRIMARY KEY,
    NOME VARCHAR(200) NOT NULL,
    CPF VARCHAR(14) NOT NULL,
    CONTRIBUICOES INTEGER DEFAULT 0,
    ID_TIPO INTEGER NOT NULL
);

CREATE TABLE imdb.NOTICIA(
	ID INTEGER PRIMARY KEY,
    DATA_LANCAMENTO DATE NOT NULL,
    TEXTO VARCHAR(1000) NOT NULL,
    ID_USUARIO INTEGER NOT NULL
);

CREATE TABLE imdb.CRITICA(
	ID_FILME INTEGER NOT NULL,
    ID_USUARIO INTEGER NOT NULL,
    TEXTO VARCHAR(500),
    NOTA FLOAT NOT NULL 	
);

CREATE TABLE imdb.COMENTARIO(
    ID INTEGER PRIMARY KEY,
    ID_FILME INTEGER NOT NULL,
    ID_USUARIO INTEGER NOT NULL,
    TEXTO VARCHAR(500) NOT NULL     
);

CREATE TABLE imdb.FILME(
    ID_ASSUNTO INTEGER PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    NOTA DECIMAL,
    DATA_ESTREIA DATE,
    ID_GENERO INTEGER NOT NULL
);

CREATE TABLE imdb.GENERO(
    ID INTEGER PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL
);

CREATE TABLE imdb.PROFISSIONAL(
    ID_ASSUNTO INTEGER PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(14) NOT NULL
);

CREATE TABLE imdb.TIPO_PARTICIPACAO(
	ID INTEGER PRIMARY KEY,
    NOME_FUNCAO VARCHAR(200) NOT NULL
);

CREATE TABLE imdb.PARTICIPA_DE(
	ID_FILME INTEGER NOT NULL,
    ID_PROFISSIONAL INTEGER NOT NULL,
    ID_TIPO_PARTICIPACAO INTEGER NOT NULL
);

CREATE TABLE imdb.SOBRE(
    ID_ASSUNTO INTEGER,
    ID_NOTICIA INTEGER
);

CREATE TABLE imdb.ASSUNTO(
    ID INTEGER PRIMARY KEY,
    ID_TIPO INTEGER NOT NULL
);

CREATE TABLE imdb.TIPO_ASSUNTO(
	ID INTEGER PRIMARY KEY,
    TIPO VARCHAR(200) NOT NULL
);

--ALTER TABLES

--ASSUNTO
ALTER TABLE imdb.ASSUNTO
ADD CONSTRAINT FK_TIPO_ASSUNTO
FOREIGN KEY (ID_TIPO) REFERENCES imdb.TIPO_ASSUNTO(ID);

--USUARIO
ALTER TABLE imdb.USUARIO
ADD CONSTRAINT FK_TIPO_USUARIO
FOREIGN KEY (ID_TIPO) REFERENCES imdb.TIPO_USUARIO(ID);

ALTER TABLE imdb.USUARIO
ADD CONSTRAINT UN_CPF
UNIQUE(CPF);

--NOTICIA
ALTER TABLE imdb.NOTICIA
ADD CONSTRAINT FK_NOTICIA
FOREIGN KEY (ID_USUARIO) REFERENCES imdb.USUARIO(ID);

--CRITICA
ALTER TABLE imdb.CRITICA
ADD CONSTRAINT PK_CRITICA
PRIMARY KEY (ID_FILME,ID_USUARIO);

ALTER TABLE imdb.CRITICA
ADD CONSTRAINT FK_FILME
FOREIGN KEY (ID_FILME) REFERENCES imdb.FILME(ID_ASSUNTO);

ALTER TABLE imdb.CRITICA
ADD CONSTRAINT FK_USUARIO
FOREIGN KEY (ID_USUARIO) REFERENCES imdb.USUARIO(ID);

--COMENTARIO
ALTER TABLE imdb.COMENTARIO
ADD CONSTRAINT FK_FILME
FOREIGN KEY (ID_FILME) REFERENCES imdb.FILME(ID_ASSUNTO);

ALTER TABLE imdb.COMENTARIO
ADD CONSTRAINT FK_USUARIO
FOREIGN KEY (ID_USUARIO) REFERENCES imdb.USUARIO(ID);


--FILME
ALTER TABLE imdb.FILME
ADD CONSTRAINT FK_ASSUNTO
FOREIGN KEY (ID_ASSUNTO) REFERENCES imdb.ASSUNTO(ID);

ALTER TABLE imdb.FILME
ADD CONSTRAINT FK_GENERO
FOREIGN KEY (ID_GENERO) REFERENCES imdb.GENERO(ID);

--PROFISSIONAL
ALTER TABLE imdb.PROFISSIONAL
ADD CONSTRAINT UN_CPF_PROFISSIONAL
UNIQUE(CPF);

ALTER TABLE imdb.PROFISSIONAL
ADD CONSTRAINT FK_ASSUNTO
FOREIGN KEY (ID_ASSUNTO) REFERENCES imdb.ASSUNTO(ID);

--PARTICIPA_DE
ALTER TABLE imdb.PARTICIPA_DE
ADD CONSTRAINT PK_PARTICIPA_DE 
PRIMARY KEY (ID_FILME,ID_PROFISSIONAL,ID_TIPO_PARTICIPACAO);

ALTER TABLE imdb.PARTICIPA_DE
ADD CONSTRAINT FK_FILME
FOREIGN KEY (ID_FILME) REFERENCES imdb.FILME(ID_ASSUNTO);

ALTER TABLE imdb.PARTICIPA_DE
ADD CONSTRAINT FK_PROFISSIONAL
FOREIGN KEY (ID_PROFISSIONAL) REFERENCES imdb.PROFISSIONAL(ID_ASSUNTO);

ALTER TABLE imdb.PARTICIPA_DE
ADD CONSTRAINT FK_TIPO_PARTICIPACAO
FOREIGN KEY (ID_TIPO_PARTICIPACAO) REFERENCES imdb.TIPO_PARTICIPACAO(ID);

--SOBRE
ALTER TABLE imdb.SOBRE
ADD CONSTRAINT PK_SOBRE
PRIMARY KEY (ID_ASSUNTO,ID_NOTICIA);

ALTER TABLE imdb.SOBRE
ADD CONSTRAINT FK_ASSUNTO
FOREIGN KEY (ID_ASSUNTO) REFERENCES imdb.ASSUNTO(ID);

ALTER TABLE imdb.SOBRE
ADD CONSTRAINT FK_NOTICIA
FOREIGN KEY (ID_NOTICIA) REFERENCES imdb.NOTICIA(ID);