INSERT INTO imdb.TIPO_ASSUNTO(ID,TIPO) VALUES (1,'Filme');
INSERT INTO imdb.TIPO_ASSUNTO(ID,TIPO) VALUES (2,'Profissional');

INSERT INTO imdb.ASSUNTO(ID,ID_TIPO) VALUES (1,1);
INSERT INTO imdb.ASSUNTO(ID,ID_TIPO) VALUES (2,1);
INSERT INTO imdb.ASSUNTO(ID,ID_TIPO) VALUES (3,2);
INSERT INTO imdb.ASSUNTO(ID,ID_TIPO) VALUES (4,2);

INSERT INTO imdb.GENERO(ID,NOME) VALUES(1,'AVENTURA');
INSERT INTO imdb.GENERO(ID,NOME) VALUES(2,'TERROR');

INSERT INTO imdb.FILME(ID_ASSUNTO,NOME,NOTA,DATA_ESTREIA,ID_GENERO) 
               VALUES (1,'Piratas do Caribe',10,'2017-05-25',1);
INSERT INTO imdb.FILME(ID_ASSUNTO,NOME,NOTA,DATA_ESTREIA,ID_GENERO) 
               VALUES (2,'Jogos Mortais',8,'2005-02-04',2);
INSERT INTO imdb.FILME(ID_ASSUNTO,NOME,NOTA,DATA_ESTREIA,ID_GENERO) 
               VALUES (3,'Piratas do Caribe 2',7,'2017-05-25',1);

INSERT INTO imdb.TIPO_USUARIO (ID,NOME) VALUES (1,'CRITICO');

INSERT INTO imdb.USUARIO (ID,NOME,CPF,CONTRIBUICOES,ID_TIPO) VALUES (1,'Marcelo','111.111.111-11',1,1);
INSERT INTO imdb.USUARIO (ID,NOME,CPF,CONTRIBUICOES,ID_TIPO) VALUES (2,'Arthur','222.222.222-22',1,1);

INSERT INTO imdb.CRITICA (ID_FILME,ID_USUARIO,TEXTO,NOTA) VALUES (1,1,'Jigsaw é um assassino 
que possui uma marca registrada: ele deixa em suas vítimas uma cicatriz em forma de quebra-cabeças,
que faz com que elas cometam atos igonizantes para se salvar. O detetive David Tapp (Danny Glover) é designado 
para investigar os assassinatos, bem como a capturar seu autor. Porém o caminho evasivo seguido por Jigsaw leva
o detetive a desenvolver uma obsessão por capturá-lo.',8);
INSERT INTO imdb.CRITICA (ID_FILME,ID_USUARIO,TEXTO,NOTA) VALUES (3,2,'Critica 2',7);

INSERT INTO imdb.COMENTARIO (ID,ID_FILME,ID_USUARIO,TEXTO) VALUES (1,1,1,'Filme muito bom! =)');
INSERT INTO imdb.COMENTARIO (ID,ID_FILME,ID_USUARIO,TEXTO) VALUES (2,2,2,'Filme emocionante!');

INSERT INTO imdb.NOTICIA (ID,DATA_LANCAMENTO,TEXTO,ID_USUARIO) VALUES (1,'2017-11-26','Primeira notícia...',1);
INSERT INTO imdb.NOTICIA (ID,DATA_LANCAMENTO,TEXTO,ID_USUARIO) VALUES (2,'2017-11-26','Segunda notícia...',2);

INSERT INTO imdb.PROFISSIONAL (ID_ASSUNTO,NOME,CPF) VALUES (4,'Carlos','333.333.333-33');

INSERT INTO imdb.TIPO_PARTICIPACAO (ID,NOME_FUNCAO) VALUES (1,'Ator');

INSERT INTO imdb.PARTICIPA_DE (ID_FILME,ID_PROFISSIONAL,ID_TIPO_PARTICIPACAO) VALUES (1,4,1);

INSERT INTO imdb.SOBRE(ID_ASSUNTO,ID_NOTICIA) VALUES (1,1);

