package uff.ic.letstalk.corbaObjects.scs;

/**
 * corbaObjects/scs/ComponentRepositoryOperations.java . Generated by the
 * IDL-to-Java compiler (portable), version "3.2" from deployment.idl
 * Sexta-feira, 9 de Dezembro de 2005 18h26min28s BRST
 */

public interface ComponentRepositoryOperations {
	void install(uff.ic.letstalk.corbaObjects.scs.ComponentId id, String entry_point,
			boolean shared, byte[] file, String help_info)
			throws uff.ic.letstalk.corbaObjects.scs.ComponentAlreadyInstalled, 
			uff.ic.letstalk.corbaObjects.scs.IOException;

	void uninstall(uff.ic.letstalk.corbaObjects.scs.ComponentId id)
			throws uff.ic.letstalk.corbaObjects.scs.ComponentNotInstalled, 
			uff.ic.letstalk.corbaObjects.scs.IOException;

	void copy(uff.ic.letstalk.corbaObjects.scs.ComponentId id,
			uff.ic.letstalk.corbaObjects.scs.ComponentRepository rep)
			throws uff.ic.letstalk.corbaObjects.scs.ComponentAlreadyInstalled, 
			uff.ic.letstalk.corbaObjects.scs.ComponentNotInstalled;

	byte[] getComponentFile(uff.ic.letstalk.corbaObjects.scs.ComponentId id)
			throws uff.ic.letstalk.corbaObjects.scs.ComponentNotInstalled, 
			uff.ic.letstalk.corbaObjects.scs.IOException;

	uff.ic.letstalk.corbaObjects.scs.ComponentDescription getComponentDescription(
			uff.ic.letstalk.corbaObjects.scs.ComponentId id)
			throws uff.ic.letstalk.corbaObjects.scs.ComponentNotInstalled;

	uff.ic.letstalk.corbaObjects.scs.ComponentDescription[] getInstalledComponents();
} // interface ComponentRepositoryOperations
