package corbaObjects.scs;

/**
 * corbaObjects/scs/_ComponentHelpStub.java . Generated by the IDL-to-Java
 * compiler (portable), version "3.2" from deployment.idl Sexta-feira, 9 de
 * Dezembro de 2005 18h26min28s BRST
 */

public class _ComponentHelpStub extends org.omg.CORBA.portable.ObjectImpl
		implements corbaObjects.scs.ComponentHelp {

	public String getHelpInfo(corbaObjects.scs.ComponentId id)
			throws corbaObjects.scs.ComponentNotFound,
			corbaObjects.scs.HelpInfoNotAvailable {
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request("getHelpInfo",
					true);
			corbaObjects.scs.ComponentIdHelper.write($out, id);
			$in = _invoke($out);
			String $result = $in.read_string();
			return $result;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream();
			String _id = $ex.getId();
			if (_id.equals("IDL:corbaObjects/scs/ComponentNotFound:1.0"))
				throw corbaObjects.scs.ComponentNotFoundHelper.read($in);
			else if (_id
					.equals("IDL:corbaObjects/scs/HelpInfoNotAvailable:1.0"))
				throw corbaObjects.scs.HelpInfoNotAvailableHelper.read($in);
			else
				throw new org.omg.CORBA.MARSHAL(_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			return getHelpInfo(id);
		} finally {
			_releaseReply($in);
		}
	} // getHelpInfo

	// Type-specific CORBA::Object operations
	private static String[] __ids = { "IDL:corbaObjects/scs/ComponentHelp:1.0" };

	public String[] _ids() {
		return __ids.clone();
	}

	private void readObject(java.io.ObjectInputStream s)
			throws java.io.IOException {
		String str = s.readUTF();
		String[] args = null;
		java.util.Properties props = null;
		org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init(args, props)
				.string_to_object(str);
		org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)
				._get_delegate();
		_set_delegate(delegate);
	}

	private void writeObject(java.io.ObjectOutputStream s)
			throws java.io.IOException {
		String[] args = null;
		java.util.Properties props = null;
		String str = org.omg.CORBA.ORB.init(args, props).object_to_string(this);
		s.writeUTF(str);
	}
} // class _ComponentHelpStub
