package corbaObjects.scs;

/**
 * corbaObjects/scs/_ComponentCollectionStub.java . Generated by the IDL-to-Java
 * compiler (portable), version "3.2" from deployment.idl Sexta-feira, 9 de
 * Dezembro de 2005 18h26min28s BRST
 */

public class _ComponentCollectionStub extends org.omg.CORBA.portable.ObjectImpl
		implements corbaObjects.scs.ComponentCollection {

	public corbaObjects.scs.ComponentHandle[] getComponent(
			corbaObjects.scs.ComponentId id)
			throws corbaObjects.scs.InvalidName {
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request("getComponent",
					true);
			corbaObjects.scs.ComponentIdHelper.write($out, id);
			$in = _invoke($out);
			corbaObjects.scs.ComponentHandle $result[] = corbaObjects.scs.ComponentHandleSeqHelper
					.read($in);
			return $result;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream();
			String _id = $ex.getId();
			if (_id.equals("IDL:corbaObjects/scs/InvalidName:1.0"))
				throw corbaObjects.scs.InvalidNameHelper.read($in);
			throw new org.omg.CORBA.MARSHAL(_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			return getComponent(id);
		} finally {
			_releaseReply($in);
		}
	} // getComponent

	public corbaObjects.scs.ComponentHandle[] getComponents()
			throws corbaObjects.scs.InvalidName {
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request(
					"getComponents", true);
			$in = _invoke($out);
			corbaObjects.scs.ComponentHandle $result[] = corbaObjects.scs.ComponentHandleSeqHelper
					.read($in);
			return $result;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream();
			String _id = $ex.getId();
			if (_id.equals("IDL:corbaObjects/scs/InvalidName:1.0"))
				throw corbaObjects.scs.InvalidNameHelper.read($in);
			throw new org.omg.CORBA.MARSHAL(_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			return getComponents();
		} finally {
			_releaseReply($in);
		}
	} // getComponents

	// Type-specific CORBA::Object operations
	private static String[] __ids = { "IDL:corbaObjects/scs/ComponentCollection:1.0" };

	public String[] _ids() {
		return __ids.clone();
	}

	private void readObject(java.io.ObjectInputStream s)
			throws java.io.IOException {
		String str = s.readUTF();
		String[] args = null;
		java.util.Properties props = null;
		org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init(args, props)
				.string_to_object(str);
		org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)
				._get_delegate();
		_set_delegate(delegate);
	}

	private void writeObject(java.io.ObjectOutputStream s)
			throws java.io.IOException {
		String[] args = null;
		java.util.Properties props = null;
		String str = org.omg.CORBA.ORB.init(args, props).object_to_string(this);
		s.writeUTF(str);
	}
} // class _ComponentCollectionStub
