package corbaObjects.scs;

/**
 * corbaObjects/scs/_ExecutionNodeStub.java . Generated by the IDL-to-Java
 * compiler (portable), version "3.2" from deployment.idl Sexta-feira, 9 de
 * Dezembro de 2005 18h26min28s BRST
 */

@SuppressWarnings("serial")
public class _ExecutionNodeStub extends org.omg.CORBA.portable.ObjectImpl
		implements corbaObjects.scs.ExecutionNode {

	public String name() {
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request("_get_name",
					true);
			$in = _invoke($out);
			String $result = $in.read_string();
			return $result;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream();
			String _id = $ex.getId();
			throw new org.omg.CORBA.MARSHAL(_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			return name();
		} finally {
			_releaseReply($in);
		}
	} // name

	public corbaObjects.scs.IComponent startContainer(String container_name)
			throws corbaObjects.scs.ContainerAlreadyExists,
			corbaObjects.scs.InternalError {
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request(
					"startContainer", true);
			$out.write_string(container_name);
			$in = _invoke($out);
			corbaObjects.scs.IComponent $result = corbaObjects.scs.IComponentHelper
					.read($in);
			return $result;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream();
			String _id = $ex.getId();
			if (_id.equals("IDL:corbaObjects/scs/ContainerAlreadyExists:1.0"))
				throw corbaObjects.scs.ContainerAlreadyExistsHelper.read($in);
			else if (_id.equals("IDL:corbaObjects/scs/InternalError:1.0"))
				throw corbaObjects.scs.InternalErrorHelper.read($in);
			else
				throw new org.omg.CORBA.MARSHAL(_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			return startContainer(container_name);
		} finally {
			_releaseReply($in);
		}
	} // startContainer

	public corbaObjects.scs.IComponent getContainer(String container_name) {
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request("getContainer",
					true);
			$out.write_string(container_name);
			$in = _invoke($out);
			corbaObjects.scs.IComponent $result = corbaObjects.scs.IComponentHelper
					.read($in);
			return $result;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream();
			String _id = $ex.getId();
			throw new org.omg.CORBA.MARSHAL(_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			return getContainer(container_name);
		} finally {
			_releaseReply($in);
		}
	} // getContainer

	public corbaObjects.scs.ContainerDescription[] getContainers() {
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request(
					"getContainers", true);
			$in = _invoke($out);
			corbaObjects.scs.ContainerDescription $result[] = corbaObjects.scs.ContainerDescriptionSeqHelper
					.read($in);
			return $result;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream();
			String _id = $ex.getId();
			throw new org.omg.CORBA.MARSHAL(_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			return getContainers();
		} finally {
			_releaseReply($in);
		}
	} // getContainers

	// Type-specific CORBA::Object operations
	private static String[] __ids = { "IDL:corbaObjects/scs/ExecutionNode:1.0" };

	public String[] _ids() {
		return __ids.clone();
	}

	private void readObject(java.io.ObjectInputStream s)
			throws java.io.IOException {
		String str = s.readUTF();
		String[] args = null;
		java.util.Properties props = null;
		org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init(args, props)
				.string_to_object(str);
		org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)
				._get_delegate();
		_set_delegate(delegate);
	}

	private void writeObject(java.io.ObjectOutputStream s)
			throws java.io.IOException {
		String[] args = null;
		java.util.Properties props = null;
		String str = org.omg.CORBA.ORB.init(args, props).object_to_string(this);
		s.writeUTF(str);
	}
} // class _ExecutionNodeStub
