package corbaObjects.scs;

/**
 * corbaObjects/scs/_NodeRegisterStub.java . Generated by the IDL-to-Java
 * compiler (portable), version "3.2" from deployment.idl Sexta-feira, 9 de
 * Dezembro de 2005 18h26min28s BRST
 */

@SuppressWarnings("serial")
public class _NodeRegisterStub extends org.omg.CORBA.portable.ObjectImpl
		implements corbaObjects.scs.NodeRegister {

	public void register(corbaObjects.scs.IComponent node,
			corbaObjects.scs.Property[] props) {
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request("register",
					true);
			corbaObjects.scs.IComponentHelper.write($out, node);
			corbaObjects.scs.PropertySeqHelper.write($out, props);
			$in = _invoke($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream();
			String _id = $ex.getId();
			throw new org.omg.CORBA.MARSHAL(_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			register(node, props);
		} finally {
			_releaseReply($in);
		}
	} // register

	public void unregister(corbaObjects.scs.IComponent node)
			throws corbaObjects.scs.ComponentNotFound {
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request("unregister",
					true);
			corbaObjects.scs.IComponentHelper.write($out, node);
			$in = _invoke($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream();
			String _id = $ex.getId();
			if (_id.equals("IDL:corbaObjects/scs/ComponentNotFound:1.0"))
				throw corbaObjects.scs.ComponentNotFoundHelper.read($in);
			throw new org.omg.CORBA.MARSHAL(_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			unregister(node);
		} finally {
			_releaseReply($in);
		}
	} // unregister

	// Type-specific CORBA::Object operations
	private static String[] __ids = { "IDL:corbaObjects/scs/NodeRegister:1.0" };

	public String[] _ids() {
		return __ids.clone();
	}

	private void readObject(java.io.ObjectInputStream s)
			throws java.io.IOException {
		String str = s.readUTF();
		String[] args = null;
		java.util.Properties props = null;
		org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init(args, props)
				.string_to_object(str);
		org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)
				._get_delegate();
		_set_delegate(delegate);
	}

	private void writeObject(java.io.ObjectOutputStream s)
			throws java.io.IOException {
		String[] args = null;
		java.util.Properties props = null;
		String str = org.omg.CORBA.ORB.init(args, props).object_to_string(this);
		s.writeUTF(str);
	}
} // class _NodeRegisterStub
