package corbaObjects.scs;

/**
 * corbaObjects/scs/AlreadyConnected.java . Generated by the IDL-to-Java
 * compiler (portable), version "3.2" from scs.idl Sexta-feira, 9 de Dezembro de
 * 2005 18h26min26s BRST
 */

@SuppressWarnings("serial")
public final class AlreadyConnected extends org.omg.CORBA.UserException {

	public AlreadyConnected() {
		super(AlreadyConnectedHelper.id());
	} // ctor

	public AlreadyConnected(String $reason) {
		super(AlreadyConnectedHelper.id() + "  " + $reason);
	} // ctor

} // class AlreadyConnected
