package corbaObjects.scs;

/**
 * corbaObjects/scs/ComponentCollectionOperations.java . Generated by the
 * IDL-to-Java compiler (portable), version "3.2" from deployment.idl
 * Sexta-feira, 9 de Dezembro de 2005 18h26min28s BRST
 */

public interface ComponentCollectionOperations {
	corbaObjects.scs.ComponentHandle[] getComponent(
			corbaObjects.scs.ComponentId id)
			throws corbaObjects.scs.InvalidName;

	corbaObjects.scs.ComponentHandle[] getComponents()
			throws corbaObjects.scs.InvalidName;
} // interface ComponentCollectionOperations
