package corbaObjects.scs;

/**
 * corbaObjects/scs/ComponentAlreadyLoaded.java . Generated by the IDL-to-Java
 * compiler (portable), version "3.2" from deployment.idl Sexta-feira, 9 de
 * Dezembro de 2005 18h26min28s BRST
 */

@SuppressWarnings("serial")
public final class ComponentAlreadyLoaded extends org.omg.CORBA.UserException {

	public ComponentAlreadyLoaded() {
		super(ComponentAlreadyLoadedHelper.id());
	} // ctor

	public ComponentAlreadyLoaded(String $reason) {
		super(ComponentAlreadyLoadedHelper.id() + "  " + $reason);
	} // ctor

} // class ComponentAlreadyLoaded
