package corbaObjects.scs;

/**
 * corbaObjects/scs/ComponentLoaderOperations.java . Generated by the
 * IDL-to-Java compiler (portable), version "3.2" from deployment.idl
 * Sexta-feira, 9 de Dezembro de 2005 18h26min28s BRST
 */

public interface ComponentLoaderOperations {
	corbaObjects.scs.ComponentHandle load(corbaObjects.scs.ComponentId id,
			String[] args) throws corbaObjects.scs.ComponentNotFound,
			corbaObjects.scs.ComponentAlreadyLoaded,
			corbaObjects.scs.LoadFailure;

	void unload(corbaObjects.scs.ComponentHandle handle)
			throws corbaObjects.scs.ComponentNotFound;

	corbaObjects.scs.ComponentHandle[] getLoadedComponents();

	corbaObjects.scs.ComponentId[] getInstalledComponents();
} // interface ComponentLoaderOperations
