package corbaObjects.scs;

/**
 * corbaObjects/scs/ComponentId.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from deployment.idl Sexta-feira, 9 de Dezembro de
 * 2005 18h26min27s BRST
 */

@SuppressWarnings("serial")
public final class ComponentId implements org.omg.CORBA.portable.IDLEntity {
	public String name = null;

	public int version = 0;

	public ComponentId() {
	} // ctor

	public ComponentId(String _name, int _version) {
		name = _name;
		version = _version;
	} // ctor

} // class ComponentId
