package corbaObjects.scs;

/**
 * corbaObjects/scs/ComponentDescription.java . Generated by the IDL-to-Java
 * compiler (portable), version "3.2" from deployment.idl Sexta-feira, 9 de
 * Dezembro de 2005 18h26min28s BRST
 */

@SuppressWarnings("serial")
public final class ComponentDescription implements
		org.omg.CORBA.portable.IDLEntity {
	public corbaObjects.scs.ComponentId id = null;

	public String entry_point = null;

	public boolean shared = false;

	public String help_info = null;

	public ComponentDescription() {
	} // ctor

	public ComponentDescription(corbaObjects.scs.ComponentId _id,
			String _entry_point, boolean _shared, String _help_info) {
		id = _id;
		entry_point = _entry_point;
		shared = _shared;
		help_info = _help_info;
	} // ctor

} // class ComponentDescription
