package corbaObjects.scs;

/**
 * corbaObjects/scs/ComponentLoader.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from deployment.idl Sexta-feira, 9 de Dezembro de
 * 2005 18h26min28s BRST
 */

public interface ComponentLoader extends ComponentLoaderOperations,
		org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity {
} // interface ComponentLoader
