package corbaObjects.scs;

/**
 * corbaObjects/scs/ConnectionDescription.java . Generated by the IDL-to-Java
 * compiler (portable), version "3.2" from scs.idl Sexta-feira, 9 de Dezembro de
 * 2005 18h26min27s BRST
 */

@SuppressWarnings("serial")
public final class ConnectionDescription implements
		org.omg.CORBA.portable.IDLEntity {
	public int id = 0;

	public org.omg.CORBA.Object objref = null;

	public ConnectionDescription() {
	} // ctor

	public ConnectionDescription(int _id, org.omg.CORBA.Object _objref) {
		id = _id;
		objref = _objref;
	} // ctor

} // class ConnectionDescription
