package corbaObjects.scs;

/**
 * corbaObjects/scs/ContainerDescriptionSeqHolder.java . Generated by the
 * IDL-to-Java compiler (portable), version "3.2" from deployment.idl
 * Sexta-feira, 9 de Dezembro de 2005 18h26min28s BRST
 */

public final class ContainerDescriptionSeqHolder implements
		org.omg.CORBA.portable.Streamable {
	public corbaObjects.scs.ContainerDescription value[] = null;

	public ContainerDescriptionSeqHolder() {
	}

	public ContainerDescriptionSeqHolder(
			corbaObjects.scs.ContainerDescription[] initialValue) {
		value = initialValue;
	}

	public void _read(org.omg.CORBA.portable.InputStream i) {
		value = corbaObjects.scs.ContainerDescriptionSeqHelper.read(i);
	}

	public void _write(org.omg.CORBA.portable.OutputStream o) {
		corbaObjects.scs.ContainerDescriptionSeqHelper.write(o, value);
	}

	public org.omg.CORBA.TypeCode _type() {
		return corbaObjects.scs.ContainerDescriptionSeqHelper.type();
	}

}
