package corbaObjects.scs;

/**
 * corbaObjects/scs/ExecutionNodeOperations.java . Generated by the IDL-to-Java
 * compiler (portable), version "3.2" from deployment.idl Sexta-feira, 9 de
 * Dezembro de 2005 18h26min28s BRST
 */

public interface ExecutionNodeOperations {
	String name();

	corbaObjects.scs.IComponent startContainer(String container_name)
			throws corbaObjects.scs.ContainerAlreadyExists,
			corbaObjects.scs.InternalError;

	corbaObjects.scs.IComponent getContainer(String container_name);

	corbaObjects.scs.ContainerDescription[] getContainers();
} // interface ExecutionNodeOperations
