package corbaObjects.scs;

/**
 * corbaObjects/scs/FacetDescription.java . Generated by the IDL-to-Java
 * compiler (portable), version "3.2" from scs.idl Sexta-feira, 9 de Dezembro de
 * 2005 18h26min26s BRST
 */

@SuppressWarnings("serial")
public final class FacetDescription implements org.omg.CORBA.portable.IDLEntity {
	public String name = null;

	public String interface_name = null;

	public org.omg.CORBA.Object facet_ref = null;

	public FacetDescription() {
	} // ctor

	public FacetDescription(String _name, String _interface_name,
			org.omg.CORBA.Object _facet_ref) {
		name = _name;
		interface_name = _interface_name;
		facet_ref = _facet_ref;
	} // ctor

} // class FacetDescription
