package corbaObjects.scs;

/**
 * corbaObjects/scs/HelpInfoNotAvailable.java . Generated by the IDL-to-Java
 * compiler (portable), version "3.2" from deployment.idl Sexta-feira, 9 de
 * Dezembro de 2005 18h26min28s BRST
 */

@SuppressWarnings("serial")
public final class HelpInfoNotAvailable extends org.omg.CORBA.UserException {

	public HelpInfoNotAvailable() {
		super(HelpInfoNotAvailableHelper.id());
	} // ctor

	public HelpInfoNotAvailable(String $reason) {
		super(HelpInfoNotAvailableHelper.id() + "  " + $reason);
	} // ctor

} // class HelpInfoNotAvailable
