package corbaObjects.scs;

/**
 * corbaObjects/scs/InternalError.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from scs.idl Sexta-feira, 9 de Dezembro de 2005
 * 18h26min26s BRST
 */

@SuppressWarnings("serial")
public final class InternalError extends org.omg.CORBA.UserException {

	public InternalError() {
		super(InternalErrorHelper.id());
	} // ctor

	public InternalError(String $reason) {
		super(InternalErrorHelper.id() + "  " + $reason);
	} // ctor

} // class InternalError
