package corbaObjects.scs;

/**
 * corbaObjects/scs/InvalidConnection.java . Generated by the IDL-to-Java
 * compiler (portable), version "3.2" from scs.idl Sexta-feira, 9 de Dezembro de
 * 2005 18h26min26s BRST
 */

@SuppressWarnings("serial")
public final class InvalidConnection extends org.omg.CORBA.UserException {

	public InvalidConnection() {
		super(InvalidConnectionHelper.id());
	} // ctor

	public InvalidConnection(String $reason) {
		super(InvalidConnectionHelper.id() + "  " + $reason);
	} // ctor

} // class InvalidConnection
