package corbaObjects.scs;

/**
 * corbaObjects/scs/IOException.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from deployment.idl Sexta-feira, 9 de Dezembro de
 * 2005 18h26min28s BRST
 */

@SuppressWarnings("serial")
public final class IOException extends org.omg.CORBA.UserException {

	public IOException() {
		super(IOExceptionHelper.id());
	} // ctor

	public IOException(String $reason) {
		super(IOExceptionHelper.id() + "  " + $reason);
	} // ctor

} // class IOException
