package corbaObjects.scs;

/**
 * corbaObjects/scs/LoadFailureHolder.java . Generated by the IDL-to-Java
 * compiler (portable), version "3.2" from deployment.idl Sexta-feira, 9 de
 * Dezembro de 2005 18h26min28s BRST
 */

public final class LoadFailureHolder implements
		org.omg.CORBA.portable.Streamable {
	public corbaObjects.scs.LoadFailure value = null;

	public LoadFailureHolder() {
	}

	public LoadFailureHolder(corbaObjects.scs.LoadFailure initialValue) {
		value = initialValue;
	}

	public void _read(org.omg.CORBA.portable.InputStream i) {
		value = corbaObjects.scs.LoadFailureHelper.read(i);
	}

	public void _write(org.omg.CORBA.portable.OutputStream o) {
		corbaObjects.scs.LoadFailureHelper.write(o, value);
	}

	public org.omg.CORBA.TypeCode _type() {
		return corbaObjects.scs.LoadFailureHelper.type();
	}

}
