package corbaObjects.scs;

/**
 * corbaObjects/scs/NameListHolder.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from scs.idl Sexta-feira, 9 de Dezembro de 2005
 * 18h26min26s BRST
 */

public final class NameListHolder implements org.omg.CORBA.portable.Streamable {
	public String value[] = null;

	public NameListHolder() {
	}

	public NameListHolder(String[] initialValue) {
		value = initialValue;
	}

	public void _read(org.omg.CORBA.portable.InputStream i) {
		value = corbaObjects.scs.NameListHelper.read(i);
	}

	public void _write(org.omg.CORBA.portable.OutputStream o) {
		corbaObjects.scs.NameListHelper.write(o, value);
	}

	public org.omg.CORBA.TypeCode _type() {
		return corbaObjects.scs.NameListHelper.type();
	}

}
