package corbaObjects.scs;

/**
 * corbaObjects/scs/NoConnectionHolder.java . Generated by the IDL-to-Java
 * compiler (portable), version "3.2" from scs.idl Sexta-feira, 9 de Dezembro de
 * 2005 18h26min26s BRST
 */

public final class NoConnectionHolder implements
		org.omg.CORBA.portable.Streamable {
	public corbaObjects.scs.NoConnection value = null;

	public NoConnectionHolder() {
	}

	public NoConnectionHolder(corbaObjects.scs.NoConnection initialValue) {
		value = initialValue;
	}

	public void _read(org.omg.CORBA.portable.InputStream i) {
		value = corbaObjects.scs.NoConnectionHelper.read(i);
	}

	public void _write(org.omg.CORBA.portable.OutputStream o) {
		corbaObjects.scs.NoConnectionHelper.write(o, value);
	}

	public org.omg.CORBA.TypeCode _type() {
		return corbaObjects.scs.NoConnectionHelper.type();
	}

}
