package corbaObjects.scs;

/**
 * corbaObjects/scs/NodeDescriptionHelper.java . Generated by the IDL-to-Java
 * compiler (portable), version "3.2" from deployment.idl Sexta-feira, 9 de
 * Dezembro de 2005 18h26min28s BRST
 */

abstract public class NodeDescriptionHelper {
	private static String _id = "IDL:corbaObjects/scs/NodeDescription/NodeDescription:1.0";

	public static void insert(org.omg.CORBA.Any a,
			corbaObjects.scs.NodeDescription that) {
		org.omg.CORBA.portable.OutputStream out = a.create_output_stream();
		a.type(type());
		write(out, that);
		a.read_value(out.create_input_stream(), type());
	}

	public static corbaObjects.scs.NodeDescription extract(org.omg.CORBA.Any a) {
		return read(a.create_input_stream());
	}

	private static org.omg.CORBA.TypeCode __typeCode = null;

	private static boolean __active = false;

	synchronized public static org.omg.CORBA.TypeCode type() {
		if (__typeCode == null) {
			synchronized (org.omg.CORBA.TypeCode.class) {
				if (__typeCode == null) {
					if (__active) {
						return org.omg.CORBA.ORB.init()
								.create_recursive_tc(_id);
					}
					__active = true;
					org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember[2];
					org.omg.CORBA.TypeCode _tcOf_members0 = null;
					_tcOf_members0 = corbaObjects.scs.IComponentHelper.type();
					_members0[0] = new org.omg.CORBA.StructMember("node",
							_tcOf_members0, null);
					_tcOf_members0 = corbaObjects.scs.PropertyHelper.type();
					_tcOf_members0 = org.omg.CORBA.ORB.init()
							.create_sequence_tc(0, _tcOf_members0);
					_tcOf_members0 = org.omg.CORBA.ORB.init().create_alias_tc(
							corbaObjects.scs.PropertySeqHelper.id(),
							"PropertySeq", _tcOf_members0);
					_members0[1] = new org.omg.CORBA.StructMember("props",
							_tcOf_members0, null);
					__typeCode = org.omg.CORBA.ORB.init().create_struct_tc(
							corbaObjects.scs.NodeDescriptionHelper.id(),
							"NodeDescription", _members0);
					__active = false;
				}
			}
		}
		return __typeCode;
	}

	public static String id() {
		return _id;
	}

	public static corbaObjects.scs.NodeDescription read(
			org.omg.CORBA.portable.InputStream istream) {
		corbaObjects.scs.NodeDescription value = new corbaObjects.scs.NodeDescription();
		value.node = corbaObjects.scs.IComponentHelper.read(istream);
		value.props = corbaObjects.scs.PropertySeqHelper.read(istream);
		return value;
	}

	public static void write(org.omg.CORBA.portable.OutputStream ostream,
			corbaObjects.scs.NodeDescription value) {
		corbaObjects.scs.IComponentHelper.write(ostream, value.node);
		corbaObjects.scs.PropertySeqHelper.write(ostream, value.props);
	}

}
