package corbaObjects.scs;

/**
 * corbaObjects/scs/NodeLookupPOA.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from deployment.idl Sexta-feira, 9 de Dezembro de
 * 2005 18h26min28s BRST
 */

@SuppressWarnings("unchecked")
public abstract class NodeLookupPOA extends org.omg.PortableServer.Servant
		implements corbaObjects.scs.NodeLookupOperations,
		org.omg.CORBA.portable.InvokeHandler {

	// Constructors

	private static java.util.Hashtable _methods = new java.util.Hashtable();

	static {
		_methods.put("getNode", new java.lang.Integer(0));
		_methods.put("getNodes", new java.lang.Integer(1));
		_methods.put("getAllNodes", new java.lang.Integer(2));
	}

	public org.omg.CORBA.portable.OutputStream _invoke(String $method,
			org.omg.CORBA.portable.InputStream in,
			org.omg.CORBA.portable.ResponseHandler $rh) {
		org.omg.CORBA.portable.OutputStream out = null;
		java.lang.Integer __method = (java.lang.Integer) _methods.get($method);
		if (__method == null)
			throw new org.omg.CORBA.BAD_OPERATION(0,
					org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

		switch (__method.intValue()) {
		case 0: // corbaObjects/scs/NodeLookup/getNode
		{
			String name = in.read_string();
			corbaObjects.scs.NodeDescription $result = null;
			$result = this.getNode(name);
			out = $rh.createReply();
			corbaObjects.scs.NodeDescriptionHelper.write(out, $result);
			break;
		}

		case 1: // corbaObjects/scs/NodeLookup/getNodes
		{
			corbaObjects.scs.Property props[] = corbaObjects.scs.PropertySeqHelper
					.read(in);
			corbaObjects.scs.NodeDescription $result[] = null;
			$result = this.getNodes(props);
			out = $rh.createReply();
			corbaObjects.scs.NodeDescriptionSeqHelper.write(out, $result);
			break;
		}

		case 2: // corbaObjects/scs/NodeLookup/getAllNodes
		{
			corbaObjects.scs.NodeDescription $result[] = null;
			$result = this.getAllNodes();
			out = $rh.createReply();
			corbaObjects.scs.NodeDescriptionSeqHelper.write(out, $result);
			break;
		}

		default:
			throw new org.omg.CORBA.BAD_OPERATION(0,
					org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
		}

		return out;
	} // _invoke

	// Type-specific CORBA::Object operations
	private static String[] __ids = { "IDL:corbaObjects/scs/NodeLookup:1.0" };

	public String[] _all_interfaces(org.omg.PortableServer.POA poa,
			byte[] objectId) {
		return __ids.clone();
	}

	public NodeLookup _this() {
		return NodeLookupHelper.narrow(super._this_object());
	}

	public NodeLookup _this(org.omg.CORBA.ORB orb) {
		return NodeLookupHelper.narrow(super._this_object(orb));
	}

} // class NodeLookupPOA
