package corbaObjects.scs;

/**
 * corbaObjects/scs/OctetSeqHolder.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from deployment.idl Sexta-feira, 9 de Dezembro de
 * 2005 18h26min27s BRST
 */

public final class OctetSeqHolder implements org.omg.CORBA.portable.Streamable {
	public byte value[] = null;

	public OctetSeqHolder() {
	}

	public OctetSeqHolder(byte[] initialValue) {
		value = initialValue;
	}

	public void _read(org.omg.CORBA.portable.InputStream i) {
		value = corbaObjects.scs.OctetSeqHelper.read(i);
	}

	public void _write(org.omg.CORBA.portable.OutputStream o) {
		corbaObjects.scs.OctetSeqHelper.write(o, value);
	}

	public org.omg.CORBA.TypeCode _type() {
		return corbaObjects.scs.OctetSeqHelper.type();
	}

}
