package corbaObjects.scs;

/**
 * corbaObjects/scs/Property.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from deployment.idl Sexta-feira, 9 de Dezembro de
 * 2005 18h26min28s BRST
 */

@SuppressWarnings("serial")
public final class Property implements org.omg.CORBA.portable.IDLEntity {
	public String name = null;

	public String value = null;

	public Property() {
	} // ctor

	public Property(String _name, String _value) {
		name = _name;
		value = _value;
	} // ctor

} // class Property
