package corbaObjects.scs;

/**
 * corbaObjects/scs/ReceptacleDescriptionHelper.java . Generated by the
 * IDL-to-Java compiler (portable), version "3.2" from scs.idl Sexta-feira, 9 de
 * Dezembro de 2005 18h26min27s BRST
 */

abstract public class ReceptacleDescriptionHelper {
	private static String _id = "IDL:corbaObjects/scs/ReceptacleDescription/ReceptacleDescription:1.0";

	public static void insert(org.omg.CORBA.Any a,
			corbaObjects.scs.ReceptacleDescription that) {
		org.omg.CORBA.portable.OutputStream out = a.create_output_stream();
		a.type(type());
		write(out, that);
		a.read_value(out.create_input_stream(), type());
	}

	public static corbaObjects.scs.ReceptacleDescription extract(
			org.omg.CORBA.Any a) {
		return read(a.create_input_stream());
	}

	private static org.omg.CORBA.TypeCode __typeCode = null;

	private static boolean __active = false;

	synchronized public static org.omg.CORBA.TypeCode type() {
		if (__typeCode == null) {
			synchronized (org.omg.CORBA.TypeCode.class) {
				if (__typeCode == null) {
					if (__active) {
						return org.omg.CORBA.ORB.init()
								.create_recursive_tc(_id);
					}
					__active = true;
					org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember[4];
					org.omg.CORBA.TypeCode _tcOf_members0 = null;
					_tcOf_members0 = org.omg.CORBA.ORB.init().create_string_tc(
							0);
					_members0[0] = new org.omg.CORBA.StructMember("name",
							_tcOf_members0, null);
					_tcOf_members0 = org.omg.CORBA.ORB.init().create_string_tc(
							0);
					_members0[1] = new org.omg.CORBA.StructMember(
							"interface_name", _tcOf_members0, null);
					_tcOf_members0 = org.omg.CORBA.ORB.init().get_primitive_tc(
							org.omg.CORBA.TCKind.tk_boolean);
					_members0[2] = new org.omg.CORBA.StructMember(
							"is_multiplex", _tcOf_members0, null);
					_tcOf_members0 = corbaObjects.scs.ConnectionDescriptionHelper
							.type();
					_tcOf_members0 = org.omg.CORBA.ORB.init()
							.create_sequence_tc(0, _tcOf_members0);
					_tcOf_members0 = org.omg.CORBA.ORB.init().create_alias_tc(
							corbaObjects.scs.ConnectionDescriptionsHelper.id(),
							"ConnectionDescriptions", _tcOf_members0);
					_members0[3] = new org.omg.CORBA.StructMember(
							"connections", _tcOf_members0, null);
					__typeCode = org.omg.CORBA.ORB.init().create_struct_tc(
							corbaObjects.scs.ReceptacleDescriptionHelper.id(),
							"ReceptacleDescription", _members0);
					__active = false;
				}
			}
		}
		return __typeCode;
	}

	public static String id() {
		return _id;
	}

	public static corbaObjects.scs.ReceptacleDescription read(
			org.omg.CORBA.portable.InputStream istream) {
		corbaObjects.scs.ReceptacleDescription value = new corbaObjects.scs.ReceptacleDescription();
		value.name = istream.read_string();
		value.interface_name = istream.read_string();
		value.is_multiplex = istream.read_boolean();
		value.connections = corbaObjects.scs.ConnectionDescriptionsHelper
				.read(istream);
		return value;
	}

	public static void write(org.omg.CORBA.portable.OutputStream ostream,
			corbaObjects.scs.ReceptacleDescription value) {
		ostream.write_string(value.name);
		ostream.write_string(value.interface_name);
		ostream.write_boolean(value.is_multiplex);
		corbaObjects.scs.ConnectionDescriptionsHelper.write(ostream,
				value.connections);
	}

}
