package corbaObjects.scs;

/**
 * corbaObjects/scs/SCSHolder.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from scs.idl Sexta-feira, 9 de Dezembro de 2005
 * 18h26min27s BRST
 */

public final class SCSHolder implements org.omg.CORBA.portable.Streamable {
	public corbaObjects.scs.SCS value = null;

	public SCSHolder() {
	}

	public SCSHolder(corbaObjects.scs.SCS initialValue) {
		value = initialValue;
	}

	public void _read(org.omg.CORBA.portable.InputStream i) {
		value = corbaObjects.scs.SCSHelper.read(i);
	}

	public void _write(org.omg.CORBA.portable.OutputStream o) {
		corbaObjects.scs.SCSHelper.write(o, value);
	}

	public org.omg.CORBA.TypeCode _type() {
		return corbaObjects.scs.SCSHelper.type();
	}

}
