package corbaObjects.scs;

/**
 * corbaObjects/scs/ShutdownFailedHolder.java . Generated by the IDL-to-Java
 * compiler (portable), version "3.2" from scs.idl Sexta-feira, 9 de Dezembro de
 * 2005 18h26min26s BRST
 */

public final class ShutdownFailedHolder implements
		org.omg.CORBA.portable.Streamable {
	public corbaObjects.scs.ShutdownFailed value = null;

	public ShutdownFailedHolder() {
	}

	public ShutdownFailedHolder(corbaObjects.scs.ShutdownFailed initialValue) {
		value = initialValue;
	}

	public void _read(org.omg.CORBA.portable.InputStream i) {
		value = corbaObjects.scs.ShutdownFailedHelper.read(i);
	}

	public void _write(org.omg.CORBA.portable.OutputStream o) {
		corbaObjects.scs.ShutdownFailedHelper.write(o, value);
	}

	public org.omg.CORBA.TypeCode _type() {
		return corbaObjects.scs.ShutdownFailedHelper.type();
	}

}
