package corbaObjects.scs;

/**
 * corbaObjects/scs/StartupFailed.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from scs.idl Sexta-feira, 9 de Dezembro de 2005
 * 18h26min26s BRST
 */

public final class StartupFailed extends org.omg.CORBA.UserException {

	public StartupFailed() {
		super(StartupFailedHelper.id());
	} // ctor

	public StartupFailed(String $reason) {
		super(StartupFailedHelper.id() + "  " + $reason);
	} // ctor

} // class StartupFailed
