package corbaObjects.scs;

/**
 * corbaObjects/scs/StartupFailedHolder.java . Generated by the IDL-to-Java
 * compiler (portable), version "3.2" from scs.idl Sexta-feira, 9 de Dezembro de
 * 2005 18h26min26s BRST
 */

public final class StartupFailedHolder implements
		org.omg.CORBA.portable.Streamable {
	public corbaObjects.scs.StartupFailed value = null;

	public StartupFailedHolder() {
	}

	public StartupFailedHolder(corbaObjects.scs.StartupFailed initialValue) {
		value = initialValue;
	}

	public void _read(org.omg.CORBA.portable.InputStream i) {
		value = corbaObjects.scs.StartupFailedHelper.read(i);
	}

	public void _write(org.omg.CORBA.portable.OutputStream o) {
		corbaObjects.scs.StartupFailedHelper.write(o, value);
	}

	public org.omg.CORBA.TypeCode _type() {
		return corbaObjects.scs.StartupFailedHelper.type();
	}

}
