package provas.s20152.p120152;

public enum Quesito {

    BATERIA,
    SAMBA_ENREDO,
    HARMONIA,
    EVOLUCAO,
    ENREDO,
    ALEGORIA,
    FANTASIA,
    COMISSAO_DE_FRENTE,
    MESTRE_SALA_E_PORTA_BANDEIRA
}
