/* Generated by Together */

package iso.iso19115.identification;

import iso.iso19115.citation.CI_Citation;
import iso.iso19115.citation.CI_ResponsibleParty;

import java.util.Vector;

/**
 * @author Luiz Leme
 * @alias MD_Identification
 * @stereotype abstract*/
abstract public class MD_Identification {
	public CI_Citation citation = null;

	public String abstract_ = null;

	public String purpose = null;

	public String credit = null;

	/**
	 * @link association
	 * @associates <{MD_ProgressCode}>*/
	public MD_ProgressCode status = null;
	public CI_ResponsibleParty pointOfContact = null;

	/**
	 * @link aggregation
	 * @associates <{iso.iso19115.maintenance.MD_MaintenanceInformation}>
	 * @supplierRole +resourceMaintenance
	 * @supplierCardinality 0..**/
	private Vector resourceMaintenance;

	/**
	 * @link aggregation
	 * @associates <{iso.iso19115.constraint.MD_Conatraints}>
	 * @supplierRole +resourceConstraints
	 * @supplierCardinality 0..**/
	private Vector resourceConatraints;

    /**
     * @link aggregation
     * @supplierCardinality 0..*
     * @supplierRole +descriptiveKeywords */
    public MD_Keywords[] descriptiveKeywords;
}
