/* Generated by Together */

package iso.iso19115.identification;

public class MD_KeywordTypeCode {
	public final static int place = 2;

	public final static int discipline = 1;

	public final static int stratum = 3;

	public final static int temporal = 4;

	public final static int theme = 5;
}
