/* Generated by Together */

package iso.iso19115.identification;

import iso.Distance;

/**
 * @stereotype union*/
public class MD_Resolution {
	public MD_RepresentativeFraction equivalenteScale = null;
	public Distance distance = null;
}
