package uff.ic.lleme.letstalk.cbobjs.corbaObjects.scs;

/**
 * corbaObjects/scs/ComponentHelpOperations.java . Generated by the IDL-to-Java
 * compiler (portable), version "3.2" from deployment.idl Sexta-feira, 9 de
 * Dezembro de 2005 18h26min28s BRST
 */

public interface ComponentHelpOperations {
	String getHelpInfo(uff.ic.lleme.letstalk.cbobjs.corbaObjects.scs.ComponentId id)
			throws uff.ic.lleme.letstalk.cbobjs.corbaObjects.scs.ComponentNotFound, 
			uff.ic.lleme.letstalk.cbobjs.corbaObjects.scs.HelpInfoNotAvailable;
} // interface ComponentHelpOperations
