package uff.ic.lleme.letstalk.cbobjs.corbaObjects.scs;

/**
 * corbaObjects/scs/ContainerDescription.java . Generated by the IDL-to-Java
 * compiler (portable), version "3.2" from deployment.idl Sexta-feira, 9 de
 * Dezembro de 2005 18h26min28s BRST
 */

@SuppressWarnings("serial")
public final class ContainerDescription implements
		org.omg.CORBA.portable.IDLEntity {
	public uff.ic.lleme.letstalk.cbobjs.corbaObjects.scs.IComponent container = null;

	public String container_name = null;

	public uff.ic.lleme.letstalk.cbobjs.corbaObjects.scs.IComponent execution_node = null;

	public ContainerDescription() {
	} // ctor

	public ContainerDescription(uff.ic.lleme.letstalk.cbobjs.corbaObjects.scs.IComponent _container,
			String _container_name, uff.ic.lleme.letstalk.cbobjs.corbaObjects.scs.IComponent _execution_node) {
		container = _container;
		container_name = _container_name;
		execution_node = _execution_node;
	} // ctor

} // class ContainerDescription
