package uff.ic.lleme.letstalk.cbobjs.corbaObjects.scs;

/**
 * corbaObjects/scs/ExceededConnectionLimitHolder.java . Generated by the
 * IDL-to-Java compiler (portable), version "3.2" from scs.idl Sexta-feira, 9 de
 * Dezembro de 2005 18h26min26s BRST
 */

public final class ExceededConnectionLimitHolder implements
		org.omg.CORBA.portable.Streamable {
	public uff.ic.lleme.letstalk.cbobjs.corbaObjects.scs.ExceededConnectionLimit value = null;

	public ExceededConnectionLimitHolder() {
	}

	public ExceededConnectionLimitHolder(
			uff.ic.lleme.letstalk.cbobjs.corbaObjects.scs.ExceededConnectionLimit initialValue) {
		value = initialValue;
	}

	public void _read(org.omg.CORBA.portable.InputStream i) {
		value = uff.ic.lleme.letstalk.cbobjs.corbaObjects.scs.ExceededConnectionLimitHelper.read(i);
	}

	public void _write(org.omg.CORBA.portable.OutputStream o) {
		uff.ic.lleme.letstalk.cbobjs.corbaObjects.scs.ExceededConnectionLimitHelper.write(o, value);
	}

	public org.omg.CORBA.TypeCode _type() {
		return uff.ic.lleme.letstalk.cbobjs.corbaObjects.scs.ExceededConnectionLimitHelper.type();
	}

}
