package uff.ic.lleme.letstalk.cbobjs.corbaObjects.scs;

/**
 * corbaObjects/scs/NodeRegisterOperations.java . Generated by the IDL-to-Java
 * compiler (portable), version "3.2" from deployment.idl Sexta-feira, 9 de
 * Dezembro de 2005 18h26min28s BRST
 */

public interface NodeRegisterOperations {
	void register(uff.ic.lleme.letstalk.cbobjs.corbaObjects.scs.IComponent node,
			uff.ic.lleme.letstalk.cbobjs.corbaObjects.scs.Property[] props);

	void unregister(uff.ic.lleme.letstalk.cbobjs.corbaObjects.scs.IComponent node)
			throws uff.ic.lleme.letstalk.cbobjs.corbaObjects.scs.ComponentNotFound;
} // interface NodeRegisterOperations
