package uff.ic.lleme.letstalk.cbobjs.corbaObjects.scs;

/**
 * corbaObjects/scs/NodeDescription.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from deployment.idl Sexta-feira, 9 de Dezembro de
 * 2005 18h26min28s BRST
 */

@SuppressWarnings("serial")
public final class NodeDescription implements org.omg.CORBA.portable.IDLEntity {
	public uff.ic.lleme.letstalk.cbobjs.corbaObjects.scs.IComponent node = null;

	public uff.ic.lleme.letstalk.cbobjs.corbaObjects.scs.Property props[] = null;

	public NodeDescription() {
	} // ctor

	public NodeDescription(uff.ic.lleme.letstalk.cbobjs.corbaObjects.scs.IComponent _node,
			uff.ic.lleme.letstalk.cbobjs.corbaObjects.scs.Property[] _props) {
		node = _node;
		props = _props;
	} // ctor

} // class NodeDescription
