package uff.ic.lleme.letstalk.cbobjs.corbaObjects.scs;

/**
 * corbaObjects/scs/SCSOperations.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from scs.idl Sexta-feira, 9 de Dezembro de 2005
 * 18h26min27s BRST
 */

public interface SCSOperations {
	uff.ic.lleme.letstalk.cbobjs.corbaObjects.scs.IComponent getIComponent(String className)
			throws uff.ic.lleme.letstalk.cbobjs.corbaObjects.scs.InternalError;

	uff.ic.lleme.letstalk.cbobjs.corbaObjects.scs.IComponent releaseIComponent(String className);
} // interface SCSOperations
