/* Generated by Together */

package iso.iso19115.spatial_representation;

import iso.Measure;

/**
 * @stereotype type*/
public class MD_Dimension {
	/**
	 * @link association
	 * @associates <{MD_DimensionTypeCode}>*/
	public String dimensionName = null;

	public int dimensionSize = 0;
	public Measure resolution = null;
}
