/* Generated by Together */

package iso.iso19115.spatial_representation;

/**
 * @author Luiz André
 * @version 1.0
 * @since 1.0
 * @alias MD_GridSpatialRepresentation*/
public class MD_GridSpatialRepresentation extends MD_SpatialRepresentation {
	/**
	 * 
	 */
	private static final long serialVersionUID = -6039798193113977762L;

	public int numberOfDimensions = 0;

	/**
	 * @supplierCardinality 1..**/
	public MD_Dimension[] axisDimensionProperties = null;

	/**
	 * @link association
	 * @associates <{MD_CellGeometryCode}>*/
	public String cellGeometry = null;

	public boolean transformationParameterAvailability = true;
}
