package uff.ic.letstalk.corbaObjects.scs;

/**
 * corbaObjects/scs/ExecutionNodeOperations.java . Generated by the IDL-to-Java
 * compiler (portable), version "3.2" from deployment.idl Sexta-feira, 9 de
 * Dezembro de 2005 18h26min28s BRST
 */

public interface ExecutionNodeOperations {
	String name();

	uff.ic.letstalk.corbaObjects.scs.IComponent startContainer(String container_name)
			throws uff.ic.letstalk.corbaObjects.scs.ContainerAlreadyExists, 
			uff.ic.letstalk.corbaObjects.scs.InternalError;

	uff.ic.letstalk.corbaObjects.scs.IComponent getContainer(String container_name);

	uff.ic.letstalk.corbaObjects.scs.ContainerDescription[] getContainers();
} // interface ExecutionNodeOperations
