package corbaObjects.letstalk.usermanager;

/**
 * corbaObjects/letstalk/usermanager/_UserManagerFacetStub.java . Generated by
 * the IDL-to-Java compiler (portable), version "3.2" from letstalk.idl
 * Sexta-feira, 9 de Dezembro de 2005 18h26min29s BRST
 */

public class _UserManagerFacetStub extends org.omg.CORBA.portable.ObjectImpl
		implements corbaObjects.letstalk.usermanager.UserManagerFacet {

	public corbaObjects.letstalk.usermanager.enum_type subscribe(String login,
			String password) {
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request("subscribe",
					true);
			$out.write_string(login);
			$out.write_string(password);
			$in = _invoke($out);
			corbaObjects.letstalk.usermanager.enum_type $result = corbaObjects.letstalk.usermanager.ResultHelper
					.read($in);
			return $result;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream();
			String _id = $ex.getId();
			throw new org.omg.CORBA.MARSHAL(_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			return subscribe(login, password);
		} finally {
			_releaseReply($in);
		}
	} // subscribe

	public corbaObjects.letstalk.usermanager.enum_type connect(String login,
			String password) {
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request("connect", true);
			$out.write_string(login);
			$out.write_string(password);
			$in = _invoke($out);
			corbaObjects.letstalk.usermanager.enum_type $result = corbaObjects.letstalk.usermanager.ResultHelper
					.read($in);
			return $result;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream();
			String _id = $ex.getId();
			throw new org.omg.CORBA.MARSHAL(_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			return connect(login, password);
		} finally {
			_releaseReply($in);
		}
	} // connect

	public corbaObjects.letstalk.usermanager.enum_type desconnect(String login) {
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request("desconnect",
					true);
			$out.write_string(login);
			$in = _invoke($out);
			corbaObjects.letstalk.usermanager.enum_type $result = corbaObjects.letstalk.usermanager.ResultHelper
					.read($in);
			return $result;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream();
			String _id = $ex.getId();
			throw new org.omg.CORBA.MARSHAL(_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			return desconnect(login);
		} finally {
			_releaseReply($in);
		}
	} // desconnect

	// Type-specific CORBA::Object operations
	private static String[] __ids = { "IDL:corbaObjects/letstalk/usermanager/UserManagerFacet:1.0" };

	public String[] _ids() {
		return __ids.clone();
	}

	private void readObject(java.io.ObjectInputStream s)
			throws java.io.IOException {
		String str = s.readUTF();
		String[] args = null;
		java.util.Properties props = null;
		org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init(args, props)
				.string_to_object(str);
		org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)
				._get_delegate();
		_set_delegate(delegate);
	}

	private void writeObject(java.io.ObjectOutputStream s)
			throws java.io.IOException {
		String[] args = null;
		java.util.Properties props = null;
		String str = org.omg.CORBA.ORB.init(args, props).object_to_string(this);
		s.writeUTF(str);
	}
} // class _UserManagerFacetStub
