package corbaObjects.letstalk.usermanager;

/**
 * corbaObjects/letstalk/usermanager/enum_typeHelper.java . Generated by the
 * IDL-to-Java compiler (portable), version "3.2" from letstalk.idl Sexta-feira,
 * 9 de Dezembro de 2005 18h26min29s BRST
 */

abstract public class enum_typeHelper {
	private static String _id = "IDL:corbaObjects/letstalk/usermanager/enum_type:1.0";

	public static void insert(org.omg.CORBA.Any a,
			corbaObjects.letstalk.usermanager.enum_type that) {
		org.omg.CORBA.portable.OutputStream out = a.create_output_stream();
		a.type(type());
		write(out, that);
		a.read_value(out.create_input_stream(), type());
	}

	public static corbaObjects.letstalk.usermanager.enum_type extract(
			org.omg.CORBA.Any a) {
		return read(a.create_input_stream());
	}

	private static org.omg.CORBA.TypeCode __typeCode = null;

	synchronized public static org.omg.CORBA.TypeCode type() {
		if (__typeCode == null) {
			__typeCode = org.omg.CORBA.ORB.init().create_enum_tc(
					corbaObjects.letstalk.usermanager.enum_typeHelper.id(),
					"enum_type", new String[] { "OK", "WRONGLOGIN", "ERROR" });
		}
		return __typeCode;
	}

	public static String id() {
		return _id;
	}

	public static corbaObjects.letstalk.usermanager.enum_type read(
			org.omg.CORBA.portable.InputStream istream) {
		return corbaObjects.letstalk.usermanager.enum_type.from_int(istream
				.read_long());
	}

	public static void write(org.omg.CORBA.portable.OutputStream ostream,
			corbaObjects.letstalk.usermanager.enum_type value) {
		ostream.write_long(value.value());
	}

}
