package corbaObjects.letstalk.usermanager;

/**
 * corbaObjects/letstalk/usermanager/UserManagerFacet.java . Generated by the
 * IDL-to-Java compiler (portable), version "3.2" from letstalk.idl Sexta-feira,
 * 9 de Dezembro de 2005 18h26min29s BRST
 */

public interface UserManagerFacet extends UserManagerFacetOperations,
		org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity {
} // interface UserManagerFacet
