package corbaObjects.letstalk.usermanager;

/**
 * corbaObjects/letstalk/usermanager/VectorHelper.java . Generated by the
 * IDL-to-Java compiler (portable), version "3.2" from letstalk.idl Sexta-feira,
 * 9 de Dezembro de 2005 18h26min29s BRST
 */

abstract public class VectorHelper {
	private static String _id = "IDL:corbaObjects/letstalk/usermanager/Vector:1.0";

	public static void insert(org.omg.CORBA.Any a, String[] that) {
		org.omg.CORBA.portable.OutputStream out = a.create_output_stream();
		a.type(type());
		write(out, that);
		a.read_value(out.create_input_stream(), type());
	}

	public static String[] extract(org.omg.CORBA.Any a) {
		return read(a.create_input_stream());
	}

	private static org.omg.CORBA.TypeCode __typeCode = null;

	synchronized public static org.omg.CORBA.TypeCode type() {
		if (__typeCode == null) {
			__typeCode = org.omg.CORBA.ORB.init().create_string_tc(0);
			__typeCode = org.omg.CORBA.ORB.init().create_array_tc(100,
					__typeCode);
			__typeCode = org.omg.CORBA.ORB.init().create_alias_tc(
					corbaObjects.letstalk.usermanager.VectorHelper.id(),
					"Vector", __typeCode);
		}
		return __typeCode;
	}

	public static String id() {
		return _id;
	}

	public static String[] read(org.omg.CORBA.portable.InputStream istream) {
		String value[] = null;
		value = new String[100];
		for (int _o0 = 0; _o0 < (100); ++_o0) {
			value[_o0] = istream.read_string();
		}
		return value;
	}

	public static void write(org.omg.CORBA.portable.OutputStream ostream,
			String[] value) {
		if (value.length != (100))
			throw new org.omg.CORBA.MARSHAL(0,
					org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
		for (int _i0 = 0; _i0 < (100); ++_i0) {
			ostream.write_string(value[_i0]);
		}
	}

}
